SET SEARCH_PATH TO db, public;

-- insert articles
DO $$
DECLARE
  image_id INTEGER;
  group_id INTEGER;
BEGIN

  -- insert a new image and store id in `image_id`
  INSERT INTO image (data, "contentType") VALUES (
    decode('R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==','base64'),
    'image/gif' -- its a small transparent gif...
  ) RETURNING id INTO image_id;

  -- create a new articleGroup and store id in `group_id`
  INSERT INTO "articleGroup" (id) VALUES (DEFAULT) RETURNING id INTO group_id;

  -- insert some articles
  INSERT INTO article ("fkGroup", "sourceUrl", "articleIsTrue", "fkScreenshot", heading, summary, "metricsAlteration", "metricsTrue", "fbShares", "fbLikes", "fbComments", "twRetweets", "twLikes") VALUES
    (group_1, 'https://www.welt.de/vermischtes/article1480019/Unglaublich-aber-wahr-Der-schwangere-indische-Mann.html', TRUE  , image_id, 'Der schwangere indische Mann' || group_1, 'Der 36-jährige Sanju Bhagat lässt sich mit einem ungewöhnlich dicken Bauch in ein indisches Krankenhaus einliefern, doch als die Ärzte ihn aufschneiden, überkommt sie der blanke Horror: In seinem Körper befindet sich ein zweiter Mensch.' || group_1 || '-1',  0, TRUE  , 0, 0, 0, 0, 0),
    (group_1, 'https://www.welt.de/vermischtes/article1480019/Unglaublich-aber-wahr-Der-schwangere-indische-Mann.html', TRUE  , image_id, 'Der schwangere indische Mann' || group_1, 'Der 36-jährige Sanju Bhagat lässt sich mit einem ungewöhnlich dicken Bauch in ein indisches Krankenhaus einliefern, doch als die Ärzte ihn aufschneiden, überkommt sie der blanke Horror: In seinem Körper befindet sich ein zweiter Mensch.' || group_1 || '-2',  +1, FALSE  , 0, 0, 0, 0, 0),
    (group_1, 'https://www.welt.de/vermischtes/article1480019/Unglaublich-aber-wahr-Der-schwangere-indische-Mann.html', TRUE  , image_id, 'Der schwangere indische Mann' || group_1, 'Der 36-jährige Sanju Bhagat lässt sich mit einem ungewöhnlich dicken Bauch in ein indisches Krankenhaus einliefern, doch als die Ärzte ihn aufschneiden, überkommt sie der blanke Horror: In seinem Körper befindet sich ein zweiter Mensch.' || group_1 || '-3',  -1, FALSE  , 0, 0, 0, 0, 0),
    (group_2, 'http://www.politico.eu/article/romanian-election-pits-three-men-with-same-name-against-each-other-vasile-cepoi-draguseni', TRUE , image_id, 'Romanian election pits three men with same name against each other' || group_2, 'Romanian election pits three men with same name against each other' || group_2 || '-1', 0, TRUE , 1906, 0, 0, 3, 75),
    (group_2, 'http://www.politico.eu/article/romanian-election-pits-three-men-with-same-name-against-each-other-vasile-cepoi-draguseni', TRUE , image_id, 'Romanian election pits three men with same name against each other' || group_2, 'Romanian election pits three men with same name against each other' || group_2 || '-2', +1, FALSE , 1906, 0, 0, 3, 75),
    (group_2, 'http://www.politico.eu/article/romanian-election-pits-three-men-with-same-name-against-each-other-vasile-cepoi-draguseni', TRUE , image_id, 'Romanian election pits three men with same name against each other' || group_2, 'Romanian election pits three men with same name against each other' || group_2 || '-3', -1, FALSE , 1906, 0, 0, 3, 75),
    (group_3, 'http://www.bbc.com/future/story/20170315-the-invention-of-heterosexuality', TRUE , image_id, 'The invention of heterosexuality' || group_3, 'One hundred years ago, people had a very different idea of what it means to be heterosexual. Dorland’s Medical Dictionary defined heterosexuality as an abnormal or perverted appetite toward the opposite sex.' || group_3 || '-1', 0, TRUE ,  88621,  0,  0,  83,  3064),
    (group_3, 'http://www.bbc.com/future/story/20170315-the-invention-of-heterosexuality', TRUE , image_id, 'The invention of heterosexuality' || group_3, 'One hundred years ago, people had a very different idea of what it means to be heterosexual. Dorland’s Medical Dictionary defined heterosexuality as an abnormal or perverted appetite toward the opposite sex.' || group_3 || '-2', +1, FALSE ,  88601,  0,  0,  0,  0),
    (group_3, 'http://www.bbc.com/future/story/20170315-the-invention-of-heterosexuality', TRUE , image_id, 'The invention of heterosexuality' || group_3, 'One hundred years ago, people had a very different idea of what it means to be heterosexual. Dorland’s Medical Dictionary defined heterosexuality as an abnormal or perverted appetite toward the opposite sex.' || group_3 || '-3', -1, FALSE ,  88601,  0,  0,  0,  0),
    (group_4, 'http://www.villaitaliankitchen.com/blog/post/introducing-the-pizzakini-the-worlds-most-mouthwatering-bikini', TRUE , image_id, '$10,000 Handmade Pizza Bikini' || group_4, 'Villa Italian Kitchen Launches $10,000 Handmade Bikini Made Entirely of Pizza in Celebration of National Bikini Day.' || group_4 || '-1', 0, TRUE ,  20,  0,  0,  0,  0),
    (group_4, 'http://www.villaitaliankitchen.com/blog/post/introducing-the-pizzakini-the-worlds-most-mouthwatering-bikini', TRUE , image_id, '$10,000 Handmade Pizza Bikini' || group_4, 'Villa Italian Kitchen Launches $10,000 Handmade Bikini Made Entirely of Pizza in Celebration of National Bikini Day.' || group_4 || '-2', +1, FALSE ,  88601,  0,  0,  0,  0),
    (group_4, 'http://www.villaitaliankitchen.com/blog/post/introducing-the-pizzakini-the-worlds-most-mouthwatering-bikini', TRUE , image_id, '$10,000 Handmade Pizza Bikini' || group_4, 'Villa Italian Kitchen Launches $10,000 Handmade Bikini Made Entirely of Pizza in Celebration of National Bikini Day.' || group_4 || '-3', -1, FALSE ,  88601,  0,  0,  0,  0),
    (group_5, 'http://science.orf.at/stories/2852839', TRUE , image_id, 'Gottesanbeterinnen fressen auch Vögel' || group_5, 'Mit ihren kräftigen Fangbeinen können Gottesanbeterinnen neben Insekten und Spinnen auch kleine Wirbeltiere erbeuten, darunter Frösche, Eidechsen, Salamander und Schlangen. Nun berichten Zoologen, dass die Raubinsekten auch kleine Vögel jagen und fressen.' || group_5 || '-1', 0, TRUE ,  5,  0,  0,  0,  5),
    (group_5, 'http://science.orf.at/stories/2852839', TRUE , image_id, 'Gottesanbeterinnen fressen auch Vögel' || group_5, 'Mit ihren kräftigen Fangbeinen können Gottesanbeterinnen neben Insekten und Spinnen auch kleine Wirbeltiere erbeuten, darunter Frösche, Eidechsen, Salamander und Schlangen. Nun berichten Zoologen, dass die Raubinsekten auch kleine Vögel jagen und fressen.' || group_5 || '-2', +1, FALSE ,  0,  0,  0,  0,  0),
    (group_5, 'http://science.orf.at/stories/2852839', TRUE , image_id, 'Gottesanbeterinnen fressen auch Vögel' || group_5, 'Mit ihren kräftigen Fangbeinen können Gottesanbeterinnen neben Insekten und Spinnen auch kleine Wirbeltiere erbeuten, darunter Frösche, Eidechsen, Salamander und Schlangen. Nun berichten Zoologen, dass die Raubinsekten auch kleine Vögel jagen und fressen.' || group_5 || '-3', -1, FALSE ,  0,  0,  0,  0,  0),
    (group_6, 'http://derstandard.at/2000060633382/Volvo-Kaengurus-lassen-selbstfahrende-Autos-verzweifeln', TRUE , image_id, 'Volvo: Kängurus lassen selbstfahrende Autos verzweifeln' || group_6, 'Volvos selbstfahrende Autos haben ein Problem mit Kängurus. Die Software kann laut Kevin McCann, dem Australien-Chef der schwedischen Automarke die einzigartige Fortbewegungsart der Tiere nicht analysieren und dementsprechend reagieren. Bei Rentieren und Elchen hingegen würde das selbstfahrende Auto bereits adäquat reagieren.' || group_6 || '-1', 0, TRUE ,  156,  0,  0,  0,  7),
    (group_6, 'http://derstandard.at/2000060633382/Volvo-Kaengurus-lassen-selbstfahrende-Autos-verzweifeln', TRUE , image_id, 'Volvo: Kängurus lassen selbstfahrende Autos verzweifeln' || group_6, 'Volvos selbstfahrende Autos haben ein Problem mit Kängurus. Die Software kann laut Kevin McCann, dem Australien-Chef der schwedischen Automarke die einzigartige Fortbewegungsart der Tiere nicht analysieren und dementsprechend reagieren. Bei Rentieren und Elchen hingegen würde das selbstfahrende Auto bereits adäquat reagieren.' || group_6 || '-2', +1, FALSE ,  88601,  0,  0,  0,  0),
    (group_6, 'http://derstandard.at/2000060633382/Volvo-Kaengurus-lassen-selbstfahrende-Autos-verzweifeln', TRUE , image_id, 'Volvo: Kängurus lassen selbstfahrende Autos verzweifeln' || group_6, 'Volvos selbstfahrende Autos haben ein Problem mit Kängurus. Die Software kann laut Kevin McCann, dem Australien-Chef der schwedischen Automarke die einzigartige Fortbewegungsart der Tiere nicht analysieren und dementsprechend reagieren. Bei Rentieren und Elchen hingegen würde das selbstfahrende Auto bereits adäquat reagieren.' || group_6 || '-3', -1, FALSE ,  88601,  0,  0,  0,  0),
    (group_7, 'http://indianexpress.com/article/india/india-news-india/assam-unique-frog-wedding-organised-to-appease-rain-god-4400839', TRUE , image_id, 'Frog Wedding organised to appease rain god' || group_7, 'According to mythological belief, holding a frog marriage ensures ample rainfall. As part of the wedding, a wild female frog is married off to a wooden figurine, representative of the Hindu god of rain, Indra.' || group_7 || '-1', 0, TRUE ,  13,  0,  0,  0,  9),
    (group_7, 'http://indianexpress.com/article/india/india-news-india/assam-unique-frog-wedding-organised-to-appease-rain-god-4400839', TRUE , image_id, 'Frog Wedding organised to appease rain god' || group_7, 'According to mythological belief, holding a frog marriage ensures ample rainfall. As part of the wedding, a wild female frog is married off to a wooden figurine, representative of the Hindu god of rain, Indra.' || group_7 || '-2', +1, FALSE ,  88601,  0,  0,  0,  0),
    (group_7, 'http://indianexpress.com/article/india/india-news-india/assam-unique-frog-wedding-organised-to-appease-rain-god-4400839', TRUE , image_id, 'Frog Wedding organised to appease rain god' || group_7, 'According to mythological belief, holding a frog marriage ensures ample rainfall. As part of the wedding, a wild female frog is married off to a wooden figurine, representative of the Hindu god of rain, Indra.' || group_7 || '-3', -1, FALSE ,  88601,  0,  0,  0,  0),
    (group_8, 'https://www.wired.com/story/lone-star-tick-that-gives-people-meat-allergies-may-be-spreading', TRUE , image_id, 'Tick Gives People Meat Allergies' || group_8, ' In the last decade and a half, thousands of previously protein-loving Americans have developed a dangerous allergy to meat. And they all have one thing in common: the lone star tick.' || group_8 || '-1', 0, TRUE ,  115564,  0,  0,  123,  13046),
    (group_8, 'https://www.wired.com/story/lone-star-tick-that-gives-people-meat-allergies-may-be-spreading', TRUE , image_id, 'Tick Gives People Meat Allergies' || group_8, ' In the last decade and a half, thousands of previously protein-loving Americans have developed a dangerous allergy to meat. And they all have one thing in common: the lone star tick.' || group_8 || '-2', +1, FALSE ,  88601,  0,  0,  0,  0),
    (group_8, 'https://www.wired.com/story/lone-star-tick-that-gives-people-meat-allergies-may-be-spreading', TRUE , image_id, 'Tick Gives People Meat Allergies' || group_8, ' In the last decade and a half, thousands of previously protein-loving Americans have developed a dangerous allergy to meat. And they all have one thing in common: the lone star tick.' || group_8 || '-3', -1, FALSE ,  88601,  0,  0,  0,  0),
    (group_9, 'http://www.abc.net.au/news/2016-12-12/no-one-home-after-seven-hour-police-standoff-in-melton/8114164', TRUE , image_id, 'Polizei belagert 7 Stunden lang leeres Haus' || group_9, 'Police have been left red-faced after embarking on a seven-hour standoff outside a Melton house west of Melbourne, only to discover no-one was inside.' || group_9 || '-1', 0, TRUE ,  17835,  0,  0,  0,  0),
    (group_9, 'http://www.abc.net.au/news/2016-12-12/no-one-home-after-seven-hour-police-standoff-in-melton/8114164', TRUE , image_id, 'Polizei belagert 7 Stunden lang leeres Haus' || group_9, 'Police have been left red-faced after embarking on a seven-hour standoff outside a Melton house west of Melbourne, only to discover no-one was inside.' || group_9 || '-2', +1, FALSE ,  88601,  0,  0,  0,  0),
    (group_9, 'http://www.abc.net.au/news/2016-12-12/no-one-home-after-seven-hour-police-standoff-in-melton/8114164', TRUE , image_id, 'Polizei belagert 7 Stunden lang leeres Haus' || group_9, 'Police have been left red-faced after embarking on a seven-hour standoff outside a Melton house west of Melbourne, only to discover no-one was inside.' || group_9 || '-3', -1, FALSE ,  88601,  0,  0,  0,  0),
    (group_10, 'http://kxan.com/2017/04/19/drug-sniffing-lizard-joins-arizona-police-force', FALSE , image_id, 'Drug-sniffing lizard joins Arizona police force' || group_10, 'One hard working reptile in Arizona is making a name for himself. This frenzy all began when the Avondale Police Department posted these photos on Facebook of the chief swearing in the department’s pet bearded dragon.' || group_10 || '-1', 0, TRUE ,  1244,  0,  0,  15,  21),
    (group_10, 'http://kxan.com/2017/04/19/drug-sniffing-lizard-joins-arizona-police-force', FALSE , image_id, 'Drug-sniffing lizard joins Arizona police force' || group_10, 'One hard working reptile in Arizona is making a name for himself. This frenzy all began when the Avondale Police Department posted these photos on Facebook of the chief swearing in the department’s pet bearded dragon.' || group_10 || '-2', +1, FALSE ,  88601,  0,  0,  0,  0),
    (group_10, 'http://kxan.com/2017/04/19/drug-sniffing-lizard-joins-arizona-police-force', FALSE , image_id, 'Drug-sniffing lizard joins Arizona police force' || group_10, 'One hard working reptile in Arizona is making a name for himself. This frenzy all began when the Avondale Police Department posted these photos on Facebook of the chief swearing in the department’s pet bearded dragon.' || group_10 || '-3', -1, FALSE ,  88601,  0,  0,  0,  0),
    (group_11, 'http://www.snopes.com/pregnant/youngestmother.asp', TRUE , image_id, 'World’s Youngest Mother — 5 Years Old' || group_11, 'The youngest mother on record was a five-year-old Peruvian girl.' || group_11 || '-1', 0, TRUE ,  3311,  0,  0,  0,  11),
    (group_11, 'http://www.snopes.com/pregnant/youngestmother.asp', TRUE , image_id, 'World’s Youngest Mother — 5 Years Old' || group_11, 'The youngest mother on record was a five-year-old Peruvian girl.' || group_11 || '-2', +1, FALSE ,  88601,  0,  0,  0,  0),
    (group_11, 'http://www.snopes.com/pregnant/youngestmother.asp', TRUE , image_id, 'World’s Youngest Mother — 5 Years Old' || group_11, 'The youngest mother on record was a five-year-old Peruvian girl.' || group_11 || '-3', -1, FALSE ,  88601,  0,  0,  0,  0),
    (group_12, 'https://www.newscientist.com/article/2129185-female-dragonflies-fake-sudden-death-to-avoid-male-advances/', TRUE , image_id, 'Female dragonflies fake sudden death to avoid male advances' || group_12, 'Female dragonflies use an extreme tactic to get rid of unwanted suitors: they drop out the sky and then pretend to be dead.' || group_12 || '-1', 0, TRUE ,  241973,  0,  0,  772,  1100),
    (group_12, 'https://www.newscientist.com/article/2129185-female-dragonflies-fake-sudden-death-to-avoid-male-advances/', TRUE , image_id, 'Female dragonflies fake sudden death to avoid male advances' || group_12, 'Female dragonflies use an extreme tactic to get rid of unwanted suitors: they drop out the sky and then pretend to be dead.' || group_12 || '-2', +1, FALSE ,  88601,  0,  0,  0,  0),
    (group_12, 'https://www.newscientist.com/article/2129185-female-dragonflies-fake-sudden-death-to-avoid-male-advances/', TRUE , image_id, 'Female dragonflies fake sudden death to avoid male advances' || group_12, 'Female dragonflies use an extreme tactic to get rid of unwanted suitors: they drop out the sky and then pretend to be dead.' || group_12 || '-3', -1, FALSE ,  88601,  0,  0,  0,  0),
    (group_13, 'http://www.independent.co.uk/environment/prince-charles-squirrels-nutella-sterilise-plans-backs-grey-red-a7597481.html', TRUE , image_id, 'Prince Charles backs plan to use Nutella as bait to sterilise grey squirrels' || group_13, 'Prince Charles has backed a government plan to sterilise grey squirrels using traps filled with Nutella, in a bid to protect their smaller red cousins.' || group_13 || '-1', 0, TRUE ,  616,  0,  0,  25,  120),
    (group_13, 'http://www.independent.co.uk/environment/prince-charles-squirrels-nutella-sterilise-plans-backs-grey-red-a7597481.html', TRUE , image_id, 'Prince Charles backs plan to use Nutella as bait to sterilise grey squirrels' || group_13, 'Prince Charles has backed a government plan to sterilise grey squirrels using traps filled with Nutella, in a bid to protect their smaller red cousins.' || group_13 || '-2', +1, FALSE ,  88601,  0,  0,  0,  0),
    (group_13, 'http://www.independent.co.uk/environment/prince-charles-squirrels-nutella-sterilise-plans-backs-grey-red-a7597481.html', TRUE , image_id, 'Prince Charles backs plan to use Nutella as bait to sterilise grey squirrels' || group_13, 'Prince Charles has backed a government plan to sterilise grey squirrels using traps filled with Nutella, in a bid to protect their smaller red cousins.' || group_13 || '-3', -1, FALSE ,  88601,  0,  0,  0,  0),
    (group_14, 'https://www.baysidestarnews.com.au/news/judge-praises-drug-dealer-its-good-business-model/3171155', TRUE , image_id, 'Judge praises drug dealer for good business model' || group_14, 'A Queensland Supreme Court judge has praised a drug dealer for his savvy business skills in running a methamphetamine operation. Justice Ann Lyons yesterday told Brodie Gary Satterley that it obviously wasnt the best business, but its a good business model.' || group_14 || '-1', 0, TRUE ,  616,  0,  0,  25,  120),
    (group_14, 'https://www.baysidestarnews.com.au/news/judge-praises-drug-dealer-its-good-business-model/3171155', TRUE , image_id, 'Judge praises drug dealer for good business model' || group_14, 'A Queensland Supreme Court judge has praised a drug dealer for his savvy business skills in running a methamphetamine operation. Justice Ann Lyons yesterday told Brodie Gary Satterley that it obviously wasnt the best business, but its a good business model.' || group_14 || '-2', +1, FALSE ,  88601,  0,  0,  0,  0),
    (group_14, 'https://www.baysidestarnews.com.au/news/judge-praises-drug-dealer-its-good-business-model/3171155', TRUE , image_id, 'Judge praises drug dealer for good business model' || group_14, 'A Queensland Supreme Court judge has praised a drug dealer for his savvy business skills in running a methamphetamine operation. Justice Ann Lyons yesterday told Brodie Gary Satterley that it obviously wasnt the best business, but its a good business model.' || group_14 || '-3', -1, FALSE ,  88601,  0,  0,  0,  0),
    (group_15, 'https://ourworldindata.org/war-and-peace', TRUE , image_id, 'We are living in the most peaceful time in our species existence' || group_15, 'Data shows that we are currently living in the most peaceful time in our species’ existence.' || group_15 || '-1', 0, TRUE ,  884,  0,  0,  25,  406),
    (group_15, 'https://ourworldindata.org/war-and-peace', TRUE , image_id, 'We are living in the most peaceful time in our species existence' || group_15, 'Data shows that we are currently living in the most peaceful time in our species’ existence.' || group_15 || '-2', +1, FALSE ,  88601,  0,  0,  0,  0),
    (group_15, 'https://ourworldindata.org/war-and-peace', TRUE , image_id, 'We are living in the most peaceful time in our species existence' || group_15, 'Data shows that we are currently living in the most peaceful time in our species’ existence.' || group_15 || '-3', -1, FALSE ,  88601,  0,  0,  0,  0),
    (group_16, 'http://www.spiegel.de/wissenschaft/mensch/kannibalismus-im-kaloriencheck-naehrwerte-von-mensch-und-tier-a-1141957.html', TRUE , image_id, 'Nährwert von Menschenfleisch: Kannibalismus zahlt sich nicht aus' || group_16, 'In der Steinzeit sollen hier und da Kannibalen am Werk gewesen sein, glauben Archäologen. Doch wie nahrhaft war ein Urmensch überhaupt? Ein Forscher hat nun eine makabere Kalorienrechnung aufgemacht.' || group_16 || '-1', 0, TRUE ,  216,  0,  0,  4,  40),
    (group_16, 'http://www.spiegel.de/wissenschaft/mensch/kannibalismus-im-kaloriencheck-naehrwerte-von-mensch-und-tier-a-1141957.html', TRUE , image_id, 'Nährwert von Menschenfleisch: Kannibalismus zahlt sich nicht aus' || group_16, 'In der Steinzeit sollen hier und da Kannibalen am Werk gewesen sein, glauben Archäologen. Doch wie nahrhaft war ein Urmensch überhaupt? Ein Forscher hat nun eine makabere Kalorienrechnung aufgemacht.' || group_16 || '-2', +1, FALSE ,  88601,  0,  0,  0,  0),
    (group_16, 'http://www.spiegel.de/wissenschaft/mensch/kannibalismus-im-kaloriencheck-naehrwerte-von-mensch-und-tier-a-1141957.html', TRUE , image_id, 'Nährwert von Menschenfleisch: Kannibalismus zahlt sich nicht aus' || group_16, 'In der Steinzeit sollen hier und da Kannibalen am Werk gewesen sein, glauben Archäologen. Doch wie nahrhaft war ein Urmensch überhaupt? Ein Forscher hat nun eine makabere Kalorienrechnung aufgemacht.' || group_16 || '-3', -1, FALSE ,  88601,  0,  0,  0,  0),
    (group_17, 'https://consumerist.com/2017/02/08/factory-that-made-samsung-galaxy-note-7-batteries-catches-fire-yes-really', TRUE , image_id, 'Factory That Made Samsung Galaxy Note 7 Batteries Catches Fire (Yes, Really)' || group_17, 'A factory in China that manufactured batteries for the now-defunct Samsung Galaxy Note 7 line of phones — all recalled due to their propensity for the batteries to burst into flame — itself suffered a fire this morning.' || group_17 || '-1', 0, TRUE ,  1874,  0,  0,  0,  43),
    (group_17, 'https://consumerist.com/2017/02/08/factory-that-made-samsung-galaxy-note-7-batteries-catches-fire-yes-really', TRUE , image_id, 'Factory That Made Samsung Galaxy Note 7 Batteries Catches Fire (Yes, Really)' || group_17, 'A factory in China that manufactured batteries for the now-defunct Samsung Galaxy Note 7 line of phones — all recalled due to their propensity for the batteries to burst into flame — itself suffered a fire this morning.' || group_17 || '-2', +1, FALSE ,  88601,  0,  0,  0,  0),
    (group_17, 'https://consumerist.com/2017/02/08/factory-that-made-samsung-galaxy-note-7-batteries-catches-fire-yes-really', TRUE , image_id, 'Factory That Made Samsung Galaxy Note 7 Batteries Catches Fire (Yes, Really)' || group_17, 'A factory in China that manufactured batteries for the now-defunct Samsung Galaxy Note 7 line of phones — all recalled due to their propensity for the batteries to burst into flame — itself suffered a fire this morning.' || group_17 || '-3', -1, FALSE ,  88601,  0,  0,  0,  0),
    (group_18, 'https://kurier.at/leben/hater-dating-app-fuer-menschen-die-dieselben-dinge-hassen/244.610.244', TRUE , image_id, 'Dating-App für Menschen, die dieselben Dinge hassen' || group_18, 'Nach Bumble, Whispar und 3nder kommt jetzt Hater, eine Dating-App à la Tinder für Menschen, die dieselben Dinge verabscheuen.' || group_18 || '-1', 0, TRUE ,  8,  0,  0,  0,  0),
    (group_18, 'https://kurier.at/leben/hater-dating-app-fuer-menschen-die-dieselben-dinge-hassen/244.610.244', TRUE , image_id, 'Dating-App für Menschen, die dieselben Dinge hassen' || group_18, 'Nach Bumble, Whispar und 3nder kommt jetzt Hater, eine Dating-App à la Tinder für Menschen, die dieselben Dinge verabscheuen.' || group_18 || '-2', +1, FALSE ,  88601,  0,  0,  0,  0),
    (group_18, 'https://kurier.at/leben/hater-dating-app-fuer-menschen-die-dieselben-dinge-hassen/244.610.244', TRUE , image_id, 'Dating-App für Menschen, die dieselben Dinge hassen' || group_18, 'Nach Bumble, Whispar und 3nder kommt jetzt Hater, eine Dating-App à la Tinder für Menschen, die dieselben Dinge verabscheuen.' || group_18 || '-3', -1, FALSE ,  88601,  0,  0,  0,  0),
    (group_19, 'http://www.taz.de/Kirche-beim-Christopher-Street-Day/!5423867', FALSE , image_id, 'Kondome mit Luthers Segen' || group_19, 'Beim Berliner CSD wird die Evangelische Kirche erstmals mit einem Partywagen dabei sein. Gleitgel und Kondome sollen geworfen werden.' || group_19 || '-1', 0, TRUE ,  1562,  0,  0,  1,  6),
    (group_19, 'http://www.taz.de/Kirche-beim-Christopher-Street-Day/!5423867', FALSE , image_id, 'Kondome mit Luthers Segen' || group_19, 'Beim Berliner CSD wird die Evangelische Kirche erstmals mit einem Partywagen dabei sein. Gleitgel und Kondome sollen geworfen werden.' || group_19 || '-2', +1, FALSE ,  88601,  0,  0,  0,  0),
    (group_19, 'http://www.taz.de/Kirche-beim-Christopher-Street-Day/!5423867', FALSE , image_id, 'Kondome mit Luthers Segen' || group_19, 'Beim Berliner CSD wird die Evangelische Kirche erstmals mit einem Partywagen dabei sein. Gleitgel und Kondome sollen geworfen werden.' || group_19 || '-3', -1, FALSE ,  88601,  0,  0,  0,  0),
    (group_20, 'votum24.votum1.de/de/politik/deutsche-steuerzahler-blechen-auch-noch-fuer-fuehrerscheinerwerb-durch-migranten', FALSE , image_id, 'Führerschein für Flüchtlinge kostenlos' || group_20, 'Die Bundesvereinigung der Fahrlehrerverbände (BVF) verzeichnet einen Ansturm von Asylbewerbern auf Fahrschulen. Der Grund für diesen Ansturm lässt sich leicht erklären. Die Kosten der Fahrausbildung übernimmt das Jobcenter.' || group_20 || '-1', 0, TRUE ,  77814,  0,  0,  0,  214),
    (group_20, 'votum24.votum1.de/de/politik/deutsche-steuerzahler-blechen-auch-noch-fuer-fuehrerscheinerwerb-durch-migranten', FALSE , image_id, 'Führerschein für Flüchtlinge kostenlos' || group_20, 'Die Bundesvereinigung der Fahrlehrerverbände (BVF) verzeichnet einen Ansturm von Asylbewerbern auf Fahrschulen. Der Grund für diesen Ansturm lässt sich leicht erklären. Die Kosten der Fahrausbildung übernimmt das Jobcenter.' || group_20 || '-2', +1, FALSE ,  88601,  0,  0,  0,  0),
    (group_20, 'votum24.votum1.de/de/politik/deutsche-steuerzahler-blechen-auch-noch-fuer-fuehrerscheinerwerb-durch-migranten', FALSE , image_id, 'Führerschein für Flüchtlinge kostenlos' || group_20, 'Die Bundesvereinigung der Fahrlehrerverbände (BVF) verzeichnet einen Ansturm von Asylbewerbern auf Fahrschulen. Der Grund für diesen Ansturm lässt sich leicht erklären. Die Kosten der Fahrausbildung übernimmt das Jobcenter.' || group_20 || '-3', -1, FALSE ,  88601,  0,  0,  0,  0),
    (group_21, 'http://www.das-unbekannte.de/wenn-man-grillen-geraeusche-verlangsamt-entdeckt-man-etwas-unerwartetes/', FALSE , image_id, 'Verlangsamtes Grillenzirpen klingt wie ein menschlicher Chor' || group_21, 'Jim Wilson, ein Komponist, machte zufällig eine sehr erstaunliche Entdeckung. Er nahm das Zirpen von Grillen auf, verlangsamte die Aufnahme anschließend und konnte seinen Ohren nicht trauen. Die Aufnahme hörte sich an wie ein Chor aus menschlichen Stimmen.' || group_21 || '-1', 0, TRUE ,  25095,  0,  0,  0,  0),
    (group_21, 'http://www.das-unbekannte.de/wenn-man-grillen-geraeusche-verlangsamt-entdeckt-man-etwas-unerwartetes/', FALSE , image_id, 'Verlangsamtes Grillenzirpen klingt wie ein menschlicher Chor' || group_21, 'Jim Wilson, ein Komponist, machte zufällig eine sehr erstaunliche Entdeckung. Er nahm das Zirpen von Grillen auf, verlangsamte die Aufnahme anschließend und konnte seinen Ohren nicht trauen. Die Aufnahme hörte sich an wie ein Chor aus menschlichen Stimmen.' || group_21 || '-2', +1, FALSE ,  88601,  0,  0,  0,  0),
    (group_21, 'http://www.das-unbekannte.de/wenn-man-grillen-geraeusche-verlangsamt-entdeckt-man-etwas-unerwartetes/', FALSE , image_id, 'Verlangsamtes Grillenzirpen klingt wie ein menschlicher Chor' || group_21, 'Jim Wilson, ein Komponist, machte zufällig eine sehr erstaunliche Entdeckung. Er nahm das Zirpen von Grillen auf, verlangsamte die Aufnahme anschließend und konnte seinen Ohren nicht trauen. Die Aufnahme hörte sich an wie ein Chor aus menschlichen Stimmen.' || group_21 || '-3', -1, FALSE ,  88601,  0,  0,  0,  0),
    (group_22, 'http://erstaunlich.at/index.php?option=com_content&view=article&id=3316%3Afreikarte-fuer-bordellbesuch-vom-sozialamt&catid=1%3Aerstaunliches&Itemid=1', FALSE , image_id, 'Freikarte für Bordellbesuch vom Sozialamt' || group_22, 'Wie uns aus einer sehr zuverlässigen  Quelle mitgeteilt wurde,  soll das Sozialamt Graz Gutscheine  für Bordellbesuche vergeben.  Diese gelten allerdings nicht in den Hauptstoßzeiten.' || group_22 || '-1', 0, TRUE ,  39,  0,  0,  0,  0),
    (group_22, 'http://erstaunlich.at/index.php?option=com_content&view=article&id=3316%3Afreikarte-fuer-bordellbesuch-vom-sozialamt&catid=1%3Aerstaunliches&Itemid=1', FALSE , image_id, 'Freikarte für Bordellbesuch vom Sozialamt' || group_22, 'Wie uns aus einer sehr zuverlässigen  Quelle mitgeteilt wurde,  soll das Sozialamt Graz Gutscheine  für Bordellbesuche vergeben.  Diese gelten allerdings nicht in den Hauptstoßzeiten.' || group_22 || '-2', +1, FALSE ,  88601,  0,  0,  0,  0),
    (group_22, 'http://erstaunlich.at/index.php?option=com_content&view=article&id=3316%3Afreikarte-fuer-bordellbesuch-vom-sozialamt&catid=1%3Aerstaunliches&Itemid=1', FALSE , image_id, 'Freikarte für Bordellbesuch vom Sozialamt' || group_22, 'Wie uns aus einer sehr zuverlässigen  Quelle mitgeteilt wurde,  soll das Sozialamt Graz Gutscheine  für Bordellbesuche vergeben.  Diese gelten allerdings nicht in den Hauptstoßzeiten.' || group_22 || '-3', -1, FALSE ,  88601,  0,  0,  0,  0),
    (group_23, 'https://www.facebook.com/photo.php?fbid=1816655728601073', FALSE , image_id, 'PIN am Bankomat rückwärts eintippen löst Polizeinotruf aus' || group_23, 'Werden Sie während eines Raubüberfalles dazu gezwungen, Geld vom Bankomaten abzuheben, geben Sie die PIN rückwärts (z.B. 4321 statt 1234) ein. Der Automat alarmiert sofort die Polizei. Jeder Bankomat hat diese Funktion.' || group_23 || '-1', 0, TRUE ,  1729886,  37772,  0,  0,  0),
    (group_23, 'https://www.facebook.com/photo.php?fbid=1816655728601073', FALSE , image_id, 'PIN am Bankomat rückwärts eintippen löst Polizeinotruf aus' || group_23, 'Werden Sie während eines Raubüberfalles dazu gezwungen, Geld vom Bankomaten abzuheben, geben Sie die PIN rückwärts (z.B. 4321 statt 1234) ein. Der Automat alarmiert sofort die Polizei. Jeder Bankomat hat diese Funktion.' || group_23 || '-2', +1, FALSE ,  88601,  0,  0,  0,  0),
    (group_23, 'https://www.facebook.com/photo.php?fbid=1816655728601073', FALSE , image_id, 'PIN am Bankomat rückwärts eintippen löst Polizeinotruf aus' || group_23, 'Werden Sie während eines Raubüberfalles dazu gezwungen, Geld vom Bankomaten abzuheben, geben Sie die PIN rückwärts (z.B. 4321 statt 1234) ein. Der Automat alarmiert sofort die Polizei. Jeder Bankomat hat diese Funktion.' || group_23 || '-3', -1, FALSE ,  88601,  0,  0,  0,  0),
    (group_24, 'www.krone.at/oesterreich/mehrere-waffen-in-versteck-auf-donauinsel-gefunden-vor-donauinselfest-story-575388', FALSE , image_id, 'Mehrere Waffen in Versteck auf Donauinsel gefunden' || group_24, 'Nur wenige Stunden vor Beginn des 34. Donauinselfest gibt es Aufregung um einen brisanten Fund: In einem Versteck auf der Donauinsel lagen zwei Maschinenpistolen und eine Faustfeuerwaffe, wie die Krone erfuhr. Ob es einen Zusammenhang mit der Riesenveranstaltung gibt, ist noch nicht geklärt.' || group_24 || '-1', 0, TRUE ,  145,  0,  0,  0,  0),
    (group_24, 'www.krone.at/oesterreich/mehrere-waffen-in-versteck-auf-donauinsel-gefunden-vor-donauinselfest-story-575388', FALSE , image_id, 'Mehrere Waffen in Versteck auf Donauinsel gefunden' || group_24, 'Nur wenige Stunden vor Beginn des 34. Donauinselfest gibt es Aufregung um einen brisanten Fund: In einem Versteck auf der Donauinsel lagen zwei Maschinenpistolen und eine Faustfeuerwaffe, wie die Krone erfuhr. Ob es einen Zusammenhang mit der Riesenveranstaltung gibt, ist noch nicht geklärt.' || group_24 || '-2', +1, FALSE ,  88601,  0,  0,  0,  0),
    (group_24, 'www.krone.at/oesterreich/mehrere-waffen-in-versteck-auf-donauinsel-gefunden-vor-donauinselfest-story-575388', FALSE , image_id, 'Mehrere Waffen in Versteck auf Donauinsel gefunden' || group_24, 'Nur wenige Stunden vor Beginn des 34. Donauinselfest gibt es Aufregung um einen brisanten Fund: In einem Versteck auf der Donauinsel lagen zwei Maschinenpistolen und eine Faustfeuerwaffe, wie die Krone erfuhr. Ob es einen Zusammenhang mit der Riesenveranstaltung gibt, ist noch nicht geklärt.' || group_24 || '-3', -1, FALSE ,  88601,  0,  0,  0,  0),
    (group_25, 'http://www.heute.at/oesterreich/oberoesterreich/story/Frau-lie--sich-Zelle-von-Hund-in-Eizelle-einsetzen-59767881', TRUE , image_id, 'Frau ließ sich Zelle von Hund einsetzen' || group_25, 'Im Rahmen eines Kunstprojekts wurde eine Eizelle der Künstlerin von Experten in einem Labor "entkernt" und darin eine Körperzelle ihres Hundes einpflanzt.' || group_25 || '-1', 0, TRUE ,  201,  0,  0,  2,  46),
    (group_25, 'http://www.heute.at/oesterreich/oberoesterreich/story/Frau-lie--sich-Zelle-von-Hund-in-Eizelle-einsetzen-59767881', TRUE , image_id, 'Frau ließ sich Zelle von Hund einsetzen' || group_25, 'Im Rahmen eines Kunstprojekts wurde eine Eizelle der Künstlerin von Experten in einem Labor "entkernt" und darin eine Körperzelle ihres Hundes einpflanzt.' || group_25 || '-2', +1, FALSE ,  88601,  0,  0,  0,  0),
    (group_25, 'http://www.heute.at/oesterreich/oberoesterreich/story/Frau-lie--sich-Zelle-von-Hund-in-Eizelle-einsetzen-59767881', TRUE , image_id, 'Frau ließ sich Zelle von Hund einsetzen' || group_25, 'Im Rahmen eines Kunstprojekts wurde eine Eizelle der Künstlerin von Experten in einem Labor "entkernt" und darin eine Körperzelle ihres Hundes einpflanzt.' || group_25 || '-3', -1, FALSE ,  88601,  0,  0,  0,  0),
    (group_26, 'https://netzfrauen.org/2017/06/09/plastik-reis/', FALSE , image_id, 'Gefälschter Reis aus Plastik' || group_26, 'August 2016 veröffentlichte die Europäische Behörde für Lebensmittelsicherheit (EFSA) ihren Jahresbericht über aufkommende Risiken. Unter den Top 10 Risiken: Plastik-Reis.' || group_26 || '-1', 0, TRUE ,  5629,  0,  0,  4,  4),
    (group_26, 'https://netzfrauen.org/2017/06/09/plastik-reis/', FALSE , image_id, 'Gefälschter Reis aus Plastik' || group_26, 'August 2016 veröffentlichte die Europäische Behörde für Lebensmittelsicherheit (EFSA) ihren Jahresbericht über aufkommende Risiken. Unter den Top 10 Risiken: Plastik-Reis.' || group_26 || '-2', +1, FALSE ,  88601,  0,  0,  0,  0),
    (group_26, 'https://netzfrauen.org/2017/06/09/plastik-reis/', FALSE , image_id, 'Gefälschter Reis aus Plastik' || group_26, 'August 2016 veröffentlichte die Europäische Behörde für Lebensmittelsicherheit (EFSA) ihren Jahresbericht über aufkommende Risiken. Unter den Top 10 Risiken: Plastik-Reis.' || group_26 || '-3', -1, FALSE ,  88601,  0,  0,  0,  0),
    (group_27, 'http://worldnewsdailyreport.com/7-year-old-girl-receives-breast-implants-for-christmas/', FALSE , image_id, '7-Jährige bekam Brustimplantate zu Weihnachten geschenkt' || group_27, 'Juliet Manson aus Glendale, Kalifornien bekam dieses Jahr zu Weihnachten von ihrer Mutter ein ganz besonderes Geschenk: eine Reise nach China, um sich einer Brustvergrößerung zu unterziehen.' || group_27 || '-1', 0, TRUE ,  39358,  0,  0,  0,  13),
    (group_27, 'http://worldnewsdailyreport.com/7-year-old-girl-receives-breast-implants-for-christmas/', FALSE , image_id, '7-Jährige bekam Brustimplantate zu Weihnachten geschenkt' || group_27, 'Juliet Manson aus Glendale, Kalifornien bekam dieses Jahr zu Weihnachten von ihrer Mutter ein ganz besonderes Geschenk: eine Reise nach China, um sich einer Brustvergrößerung zu unterziehen.' || group_27 || '-2', +1, FALSE ,  88601,  0,  0,  0,  0),
    (group_27, 'http://worldnewsdailyreport.com/7-year-old-girl-receives-breast-implants-for-christmas/', FALSE , image_id, '7-Jährige bekam Brustimplantate zu Weihnachten geschenkt' || group_27, 'Juliet Manson aus Glendale, Kalifornien bekam dieses Jahr zu Weihnachten von ihrer Mutter ein ganz besonderes Geschenk: eine Reise nach China, um sich einer Brustvergrößerung zu unterziehen.' || group_27 || '-3', -1, FALSE ,  88601,  0,  0,  0,  0),
    (group_28, 'http://haynoticia.es/mujer-lleva-28-anos-haciendose-pasar-ciega-no-saludar-la-gente3333/', FALSE , image_id, 'Frau täuschte Blindheit vor - 28 Jahre lang' || group_28, '57-Jährige bestätigte vor Kurzem, einen von ihren Nachbarn bereits länger gehegten Verdacht: sie habe ihre Blindheit nur vorgetäuscht. So habe sie Bekannte auf der Straße nicht mehr grüßen müssen, behauptet Carmen Jimenez' || group_28 || '-1', 0, TRUE ,  70173,  0,  0,  0,  0),
    (group_28, 'http://haynoticia.es/mujer-lleva-28-anos-haciendose-pasar-ciega-no-saludar-la-gente3333/', FALSE , image_id, 'Frau täuschte Blindheit vor - 28 Jahre lang' || group_28, '57-Jährige bestätigte vor Kurzem, einen von ihren Nachbarn bereits länger gehegten Verdacht: sie habe ihre Blindheit nur vorgetäuscht. So habe sie Bekannte auf der Straße nicht mehr grüßen müssen, behauptet Carmen Jimenez' || group_28 || '-2', +1, FALSE ,  88601,  0,  0,  0,  0),
    (group_28, 'http://haynoticia.es/mujer-lleva-28-anos-haciendose-pasar-ciega-no-saludar-la-gente3333/', FALSE , image_id, 'Frau täuschte Blindheit vor - 28 Jahre lang' || group_28, '57-Jährige bestätigte vor Kurzem, einen von ihren Nachbarn bereits länger gehegten Verdacht: sie habe ihre Blindheit nur vorgetäuscht. So habe sie Bekannte auf der Straße nicht mehr grüßen müssen, behauptet Carmen Jimenez' || group_28 || '-3', -1, FALSE ,  88601,  0,  0,  0,  0),
    (group_29, 'https://www.waz.de/politik/afd-mann-raet-frauenverbrennung-um-klima-zu-retten-id210539979.html', FALSE , image_id, 'AfD-Politiker Podeswa fordert Frauenverbrennungen gegen Klimawandel' || group_29, 'AfD-Politiker Rainer Podeswa meint zu wissen, wie man den Klimawandel stoppen kann. Seine „Empfehlung“ im Landtag, sich im Kampf gegen den Klimawandel am „Hexenhammer“ zu orientieren, hatte für Empörung gesorgt.' || group_29 || '-1', 0, TRUE ,  591,  0,  0,  0,  0),
    (group_29, 'https://www.waz.de/politik/afd-mann-raet-frauenverbrennung-um-klima-zu-retten-id210539979.html', FALSE , image_id, 'AfD-Politiker Podeswa fordert Frauenverbrennungen gegen Klimawandel' || group_29, 'AfD-Politiker Rainer Podeswa meint zu wissen, wie man den Klimawandel stoppen kann. Seine „Empfehlung“ im Landtag, sich im Kampf gegen den Klimawandel am „Hexenhammer“ zu orientieren, hatte für Empörung gesorgt.' || group_29 || '-2', +1, FALSE ,  88601,  0,  0,  0,  0),
    (group_29, 'https://www.waz.de/politik/afd-mann-raet-frauenverbrennung-um-klima-zu-retten-id210539979.html', FALSE , image_id, 'AfD-Politiker Podeswa fordert Frauenverbrennungen gegen Klimawandel' || group_29, 'AfD-Politiker Rainer Podeswa meint zu wissen, wie man den Klimawandel stoppen kann. Seine „Empfehlung“ im Landtag, sich im Kampf gegen den Klimawandel am „Hexenhammer“ zu orientieren, hatte für Empörung gesorgt.' || group_29 || '-3', -1, FALSE ,  88601,  0,  0,  0,  0);


END
$$;

-- insert articles with image from url
DO $$
DECLARE
  image_id INTEGER;
  group_id INTEGER;
BEGIN

  -- insert a new image and store id in `image_id`
  INSERT INTO image (data, "contentType") VALUES (
    http_get('http://lorempixel.com/400/200/'), 'image/jpeg'
  ) RETURNING id INTO image_id;

  -- create a new articleGroup and store id in `group_id`
  INSERT INTO "articleGroup" (id) VALUES (DEFAULT) RETURNING id INTO group_id;

  -- insert some articles
  INSERT INTO article ("fkGroup", "sourceUrl", "articleIsTrue", "fkScreenshot", heading, summary, "metricsAlteration", "metricsTrue", "fbShares", "fbLikes", "fbComments", "twRetweets", "twLikes") VALUES
    (group_id, 'http://some/url', TRUE  , image_id, 'true heading' || group_id, 'true summary' || group_id || '-1',  0, TRUE  , 10, 10, 10, 10, 10),
    (group_id, 'http://some/url', FALSE , image_id, 'fake heading' || group_id, 'fake summary' || group_id || '-2', +1, FALSE , 15, 15, 15, 15, 15),
    (group_id, 'http://some/url', FALSE , image_id, 'fake heading' || group_id, 'fake summary' || group_id || '-3', -1, FALSE ,  5,  5,  5,  5,  5);


END
$$;

-- create votes
DO $$
DECLARE
  vote_id INTEGER;
  article_id INTEGER;
  vote_value BOOLEAN;
BEGIN

  -- random vote (true/false)
  SELECT INTO vote_value random() > 0.5;

  -- get the next article and store only the id
  SELECT INTO article_id (SELECT id FROM getNextArticle());

  --
  INSERT INTO vote (value, "fkArticle") VALUES (vote_value, article_id) RETURNING vote.id INTO vote_id;

  RAISE NOTICE 'vote_id=%, vote_value=%, article_id=%, group=%', vote_id, vote_value, article_id, (SELECT "fkGroup" FROM article WHERE id=article_id);

END
$$;



