SET SEARCH_PATH TO db, public;

-- insert articles
DO $$
DECLARE
  image_id INTEGER;
  group_id INTEGER;
BEGIN

  -- insert a new image and store id in `image_id`
  INSERT INTO image (data, "contentType") VALUES ( http_get('http://lorempixel.com/400/200/'), 'image/jpeg') RETURNING id INTO image_id;

  -- create a new articleGroup and store id in `group_id`
  INSERT INTO "articleGroup" (id) VALUES (DEFAULT) RETURNING id INTO group_id;

  -- insert articles
  INSERT INTO article ("fkGroup", "sourceUrl", "articleIsTrue", "fkScreenshot", heading, summary, "metricsAlteration", "metricsTrue", "fbShares", "fbLikes", "fbComments", "twRetweets", "twLikes") VALUES
    (group_id, 'https://www.welt.de/vermischtes/article1480019/Unglaublich-aber-wahr-Der-schwangere-indische-Mann.html', TRUE  , image_id, 'Der schwangere indische Mann', 'Der 36-jährige Sanju Bhagat lässt sich mit einem ungewöhnlich dicken Bauch in ein indisches Krankenhaus einliefern, doch als die Ärzte ihn aufschneiden, überkommt sie der blanke Horror: In seinem Körper befindet sich ein zweiter Mensch.',  0, TRUE  , 0, 0, 0, 0, 0),
    (group_id, 'https://www.welt.de/vermischtes/article1480019/Unglaublich-aber-wahr-Der-schwangere-indische-Mann.html', TRUE  , image_id, 'Der schwangere indische Mann', 'Der 36-jährige Sanju Bhagat lässt sich mit einem ungewöhnlich dicken Bauch in ein indisches Krankenhaus einliefern, doch als die Ärzte ihn aufschneiden, überkommt sie der blanke Horror: In seinem Körper befindet sich ein zweiter Mensch.',  +1, FALSE  , 0, 0, 0, 0, 0),
    (group_id, 'https://www.welt.de/vermischtes/article1480019/Unglaublich-aber-wahr-Der-schwangere-indische-Mann.html', TRUE  , image_id, 'Der schwangere indische Mann', 'Der 36-jährige Sanju Bhagat lässt sich mit einem ungewöhnlich dicken Bauch in ein indisches Krankenhaus einliefern, doch als die Ärzte ihn aufschneiden, überkommt sie der blanke Horror: In seinem Körper befindet sich ein zweiter Mensch.',  -1, FALSE  , 0, 0, 0, 0, 0);

  INSERT INTO image (data, "contentType") VALUES ( http_get('http://lorempixel.com/400/200/'), 'image/jpeg') RETURNING id INTO image_id;
  INSERT INTO "articleGroup" (id) VALUES (DEFAULT) RETURNING id INTO group_id;
  INSERT INTO article ("fkGroup", "sourceUrl", "articleIsTrue", "fkScreenshot", heading, summary, "metricsAlteration", "metricsTrue", "fbShares", "fbLikes", "fbComments", "twRetweets", "twLikes") VALUES
    (group_id, 'http://www.politico.eu/article/romanian-election-pits-three-men-with-same-name-against-each-other-vasile-cepoi-draguseni', TRUE , image_id, 'Romanian election pits three men with same name against each other', 'Romanian election pits three men with same name against each other', 0, TRUE , 1906, 0, 0, 3, 75),
    (group_id, 'http://www.politico.eu/article/romanian-election-pits-three-men-with-same-name-against-each-other-vasile-cepoi-draguseni', TRUE , image_id, 'Romanian election pits three men with same name against each other', 'Romanian election pits three men with same name against each other', +1, FALSE , 1906, 0, 0, 3, 75),
    (group_id, 'http://www.politico.eu/article/romanian-election-pits-three-men-with-same-name-against-each-other-vasile-cepoi-draguseni', TRUE , image_id, 'Romanian election pits three men with same name against each other', 'Romanian election pits three men with same name against each other', -1, FALSE , 1906, 0, 0, 3, 75);

  INSERT INTO image (data, "contentType") VALUES ( http_get('http://lorempixel.com/400/200/'), 'image/jpeg') RETURNING id INTO image_id;
  INSERT INTO "articleGroup" (id) VALUES (DEFAULT) RETURNING id INTO group_id;
  INSERT INTO article ("fkGroup", "sourceUrl", "articleIsTrue", "fkScreenshot", heading, summary, "metricsAlteration", "metricsTrue", "fbShares", "fbLikes", "fbComments", "twRetweets", "twLikes") VALUES
    (group_id, 'http://www.bbc.com/future/story/20170315-the-invention-of-heterosexuality', TRUE , image_id, 'The invention of heterosexuality', 'One hundred years ago, people had a very different idea of what it means to be heterosexual. Dorland’s Medical Dictionary defined heterosexuality as an abnormal or perverted appetite toward the opposite sex.', 0, TRUE ,  88621,  0,  0,  83,  3064),
    (group_id, 'http://www.bbc.com/future/story/20170315-the-invention-of-heterosexuality', TRUE , image_id, 'The invention of heterosexuality', 'One hundred years ago, people had a very different idea of what it means to be heterosexual. Dorland’s Medical Dictionary defined heterosexuality as an abnormal or perverted appetite toward the opposite sex.', +1, FALSE ,  88601,  0,  0,  0,  0),
    (group_id, 'http://www.bbc.com/future/story/20170315-the-invention-of-heterosexuality', TRUE , image_id, 'The invention of heterosexuality', 'One hundred years ago, people had a very different idea of what it means to be heterosexual. Dorland’s Medical Dictionary defined heterosexuality as an abnormal or perverted appetite toward the opposite sex.', -1, FALSE ,  88601,  0,  0,  0,  0);

  INSERT INTO image (data, "contentType") VALUES ( http_get('http://lorempixel.com/400/200/'), 'image/jpeg') RETURNING id INTO image_id;
  INSERT INTO "articleGroup" (id) VALUES (DEFAULT) RETURNING id INTO group_id;
  INSERT INTO article ("fkGroup", "sourceUrl", "articleIsTrue", "fkScreenshot", heading, summary, "metricsAlteration", "metricsTrue", "fbShares", "fbLikes", "fbComments", "twRetweets", "twLikes") VALUES
    (group_id, 'http://www.villaitaliankitchen.com/blog/post/introducing-the-pizzakini-the-worlds-most-mouthwatering-bikini', TRUE , image_id, '$10,000 Handmade Pizza Bikini', 'Villa Italian Kitchen Launches $10,000 Handmade Bikini Made Entirely of Pizza in Celebration of National Bikini Day.', 0, TRUE ,  20,  0,  0,  0,  0),
    (group_id, 'http://www.villaitaliankitchen.com/blog/post/introducing-the-pizzakini-the-worlds-most-mouthwatering-bikini', TRUE , image_id, '$10,000 Handmade Pizza Bikini', 'Villa Italian Kitchen Launches $10,000 Handmade Bikini Made Entirely of Pizza in Celebration of National Bikini Day.', +1, FALSE ,  88601,  0,  0,  0,  0),
    (group_id, 'http://www.villaitaliankitchen.com/blog/post/introducing-the-pizzakini-the-worlds-most-mouthwatering-bikini', TRUE , image_id, '$10,000 Handmade Pizza Bikini', 'Villa Italian Kitchen Launches $10,000 Handmade Bikini Made Entirely of Pizza in Celebration of National Bikini Day.', -1, FALSE ,  88601,  0,  0,  0,  0);

  INSERT INTO image (data, "contentType") VALUES ( http_get('http://lorempixel.com/400/200/'), 'image/jpeg') RETURNING id INTO image_id;
  INSERT INTO "articleGroup" (id) VALUES (DEFAULT) RETURNING id INTO group_id;
  INSERT INTO article ("fkGroup", "sourceUrl", "articleIsTrue", "fkScreenshot", heading, summary, "metricsAlteration", "metricsTrue", "fbShares", "fbLikes", "fbComments", "twRetweets", "twLikes") VALUES
    (group_id, 'http://science.orf.at/stories/2852839', TRUE , image_id, 'Gottesanbeterinnen fressen auch Vögel', 'Mit ihren kräftigen Fangbeinen können Gottesanbeterinnen neben Insekten und Spinnen auch kleine Wirbeltiere erbeuten, darunter Frösche, Eidechsen, Salamander und Schlangen. Nun berichten Zoologen, dass die Raubinsekten auch kleine Vögel jagen und fressen.', 0, TRUE ,  5,  0,  0,  0,  5),
    (group_id, 'http://science.orf.at/stories/2852839', TRUE , image_id, 'Gottesanbeterinnen fressen auch Vögel', 'Mit ihren kräftigen Fangbeinen können Gottesanbeterinnen neben Insekten und Spinnen auch kleine Wirbeltiere erbeuten, darunter Frösche, Eidechsen, Salamander und Schlangen. Nun berichten Zoologen, dass die Raubinsekten auch kleine Vögel jagen und fressen.', +1, FALSE ,  0,  0,  0,  0,  0),
    (group_id, 'http://science.orf.at/stories/2852839', TRUE , image_id, 'Gottesanbeterinnen fressen auch Vögel', 'Mit ihren kräftigen Fangbeinen können Gottesanbeterinnen neben Insekten und Spinnen auch kleine Wirbeltiere erbeuten, darunter Frösche, Eidechsen, Salamander und Schlangen. Nun berichten Zoologen, dass die Raubinsekten auch kleine Vögel jagen und fressen.', -1, FALSE ,  0,  0,  0,  0,  0);

  INSERT INTO image (data, "contentType") VALUES ( http_get('http://lorempixel.com/400/200/'), 'image/jpeg') RETURNING id INTO image_id;
  INSERT INTO "articleGroup" (id) VALUES (DEFAULT) RETURNING id INTO group_id;
  INSERT INTO article ("fkGroup", "sourceUrl", "articleIsTrue", "fkScreenshot", heading, summary, "metricsAlteration", "metricsTrue", "fbShares", "fbLikes", "fbComments", "twRetweets", "twLikes") VALUES
    (group_id, 'http://derstandard.at/2000060633382/Volvo-Kaengurus-lassen-selbstfahrende-Autos-verzweifeln', TRUE , image_id, 'Volvo: Kängurus lassen selbstfahrende Autos verzweifeln', 'Volvos selbstfahrende Autos haben ein Problem mit Kängurus. Die Software kann laut Kevin McCann, dem Australien-Chef der schwedischen Automarke die einzigartige Fortbewegungsart der Tiere nicht analysieren und dementsprechend reagieren. Bei Rentieren und Elchen hingegen würde das selbstfahrende Auto bereits adäquat reagieren.', 0, TRUE ,  156,  0,  0,  0,  7),
    (group_id, 'http://derstandard.at/2000060633382/Volvo-Kaengurus-lassen-selbstfahrende-Autos-verzweifeln', TRUE , image_id, 'Volvo: Kängurus lassen selbstfahrende Autos verzweifeln', 'Volvos selbstfahrende Autos haben ein Problem mit Kängurus. Die Software kann laut Kevin McCann, dem Australien-Chef der schwedischen Automarke die einzigartige Fortbewegungsart der Tiere nicht analysieren und dementsprechend reagieren. Bei Rentieren und Elchen hingegen würde das selbstfahrende Auto bereits adäquat reagieren.', +1, FALSE ,  88601,  0,  0,  0,  0),
    (group_id, 'http://derstandard.at/2000060633382/Volvo-Kaengurus-lassen-selbstfahrende-Autos-verzweifeln', TRUE , image_id, 'Volvo: Kängurus lassen selbstfahrende Autos verzweifeln', 'Volvos selbstfahrende Autos haben ein Problem mit Kängurus. Die Software kann laut Kevin McCann, dem Australien-Chef der schwedischen Automarke die einzigartige Fortbewegungsart der Tiere nicht analysieren und dementsprechend reagieren. Bei Rentieren und Elchen hingegen würde das selbstfahrende Auto bereits adäquat reagieren.', -1, FALSE ,  88601,  0,  0,  0,  0);

  INSERT INTO image (data, "contentType") VALUES ( http_get('http://lorempixel.com/400/200/'), 'image/jpeg') RETURNING id INTO image_id;
  INSERT INTO "articleGroup" (id) VALUES (DEFAULT) RETURNING id INTO group_id;
  INSERT INTO article ("fkGroup", "sourceUrl", "articleIsTrue", "fkScreenshot", heading, summary, "metricsAlteration", "metricsTrue", "fbShares", "fbLikes", "fbComments", "twRetweets", "twLikes") VALUES
    (group_id, 'http://indianexpress.com/article/india/india-news-india/assam-unique-frog-wedding-organised-to-appease-rain-god-4400839', TRUE , image_id, 'Frog Wedding organised to appease rain god', 'According to mythological belief, holding a frog marriage ensures ample rainfall. As part of the wedding, a wild female frog is married off to a wooden figurine, representative of the Hindu god of rain, Indra.', 0, TRUE ,  13,  0,  0,  0,  9),
    (group_id, 'http://indianexpress.com/article/india/india-news-india/assam-unique-frog-wedding-organised-to-appease-rain-god-4400839', TRUE , image_id, 'Frog Wedding organised to appease rain god', 'According to mythological belief, holding a frog marriage ensures ample rainfall. As part of the wedding, a wild female frog is married off to a wooden figurine, representative of the Hindu god of rain, Indra.', +1, FALSE ,  88601,  0,  0,  0,  0),
    (group_id, 'http://indianexpress.com/article/india/india-news-india/assam-unique-frog-wedding-organised-to-appease-rain-god-4400839', TRUE , image_id, 'Frog Wedding organised to appease rain god', 'According to mythological belief, holding a frog marriage ensures ample rainfall. As part of the wedding, a wild female frog is married off to a wooden figurine, representative of the Hindu god of rain, Indra.', -1, FALSE ,  88601,  0,  0,  0,  0);

  INSERT INTO image (data, "contentType") VALUES ( http_get('http://lorempixel.com/400/200/'), 'image/jpeg') RETURNING id INTO image_id;
  INSERT INTO "articleGroup" (id) VALUES (DEFAULT) RETURNING id INTO group_id;
  INSERT INTO article ("fkGroup", "sourceUrl", "articleIsTrue", "fkScreenshot", heading, summary, "metricsAlteration", "metricsTrue", "fbShares", "fbLikes", "fbComments", "twRetweets", "twLikes") VALUES
    (group_id, 'https://www.wired.com/story/lone-star-tick-that-gives-people-meat-allergies-may-be-spreading', TRUE , image_id, 'Tick Gives People Meat Allergies', ' In the last decade and a half, thousands of previously protein-loving Americans have developed a dangerous allergy to meat. And they all have one thing in common: the lone star tick.', 0, TRUE ,  115564,  0,  0,  123,  13046),
    (group_id, 'https://www.wired.com/story/lone-star-tick-that-gives-people-meat-allergies-may-be-spreading', TRUE , image_id, 'Tick Gives People Meat Allergies', ' In the last decade and a half, thousands of previously protein-loving Americans have developed a dangerous allergy to meat. And they all have one thing in common: the lone star tick.', +1, FALSE ,  88601,  0,  0,  0,  0),
    (group_id, 'https://www.wired.com/story/lone-star-tick-that-gives-people-meat-allergies-may-be-spreading', TRUE , image_id, 'Tick Gives People Meat Allergies', ' In the last decade and a half, thousands of previously protein-loving Americans have developed a dangerous allergy to meat. And they all have one thing in common: the lone star tick.', -1, FALSE ,  88601,  0,  0,  0,  0);

  INSERT INTO image (data, "contentType") VALUES ( http_get('http://lorempixel.com/400/200/'), 'image/jpeg') RETURNING id INTO image_id;
  INSERT INTO "articleGroup" (id) VALUES (DEFAULT) RETURNING id INTO group_id;
  INSERT INTO article ("fkGroup", "sourceUrl", "articleIsTrue", "fkScreenshot", heading, summary, "metricsAlteration", "metricsTrue", "fbShares", "fbLikes", "fbComments", "twRetweets", "twLikes") VALUES
    (group_id, 'http://www.abc.net.au/news/2016-12-12/no-one-home-after-seven-hour-police-standoff-in-melton/8114164', TRUE , image_id, 'Polizei belagert 7 Stunden lang leeres Haus', 'Police have been left red-faced after embarking on a seven-hour standoff outside a Melton house west of Melbourne, only to discover no-one was inside.', 0, TRUE ,  17835,  0,  0,  0,  0),
    (group_id, 'http://www.abc.net.au/news/2016-12-12/no-one-home-after-seven-hour-police-standoff-in-melton/8114164', TRUE , image_id, 'Polizei belagert 7 Stunden lang leeres Haus', 'Police have been left red-faced after embarking on a seven-hour standoff outside a Melton house west of Melbourne, only to discover no-one was inside.', +1, FALSE ,  88601,  0,  0,  0,  0),
    (group_id, 'http://www.abc.net.au/news/2016-12-12/no-one-home-after-seven-hour-police-standoff-in-melton/8114164', TRUE , image_id, 'Polizei belagert 7 Stunden lang leeres Haus', 'Police have been left red-faced after embarking on a seven-hour standoff outside a Melton house west of Melbourne, only to discover no-one was inside.', -1, FALSE ,  88601,  0,  0,  0,  0);

  INSERT INTO image (data, "contentType") VALUES ( http_get('http://lorempixel.com/400/200/'), 'image/jpeg') RETURNING id INTO image_id;
  INSERT INTO "articleGroup" (id) VALUES (DEFAULT) RETURNING id INTO group_id;
  INSERT INTO article ("fkGroup", "sourceUrl", "articleIsTrue", "fkScreenshot", heading, summary, "metricsAlteration", "metricsTrue", "fbShares", "fbLikes", "fbComments", "twRetweets", "twLikes") VALUES
    (group_id, 'http://kxan.com/2017/04/19/drug-sniffing-lizard-joins-arizona-police-force', FALSE , image_id, 'Drug-sniffing lizard joins Arizona police force', 'One hard working reptile in Arizona is making a name for himself. This frenzy all began when the Avondale Police Department posted these photos on Facebook of the chief swearing in the department’s pet bearded dragon.', 0, TRUE ,  1244,  0,  0,  15,  21),
    (group_id, 'http://kxan.com/2017/04/19/drug-sniffing-lizard-joins-arizona-police-force', FALSE , image_id, 'Drug-sniffing lizard joins Arizona police force', 'One hard working reptile in Arizona is making a name for himself. This frenzy all began when the Avondale Police Department posted these photos on Facebook of the chief swearing in the department’s pet bearded dragon.', +1, FALSE ,  88601,  0,  0,  0,  0),
    (group_id, 'http://kxan.com/2017/04/19/drug-sniffing-lizard-joins-arizona-police-force', FALSE , image_id, 'Drug-sniffing lizard joins Arizona police force', 'One hard working reptile in Arizona is making a name for himself. This frenzy all began when the Avondale Police Department posted these photos on Facebook of the chief swearing in the department’s pet bearded dragon.', -1, FALSE ,  88601,  0,  0,  0,  0);

  INSERT INTO image (data, "contentType") VALUES ( http_get('http://lorempixel.com/400/200/'), 'image/jpeg') RETURNING id INTO image_id;
  INSERT INTO "articleGroup" (id) VALUES (DEFAULT) RETURNING id INTO group_id;
  INSERT INTO article ("fkGroup", "sourceUrl", "articleIsTrue", "fkScreenshot", heading, summary, "metricsAlteration", "metricsTrue", "fbShares", "fbLikes", "fbComments", "twRetweets", "twLikes") VALUES
    (group_id, 'http://www.snopes.com/pregnant/youngestmother.asp', TRUE , image_id, 'World’s Youngest Mother — 5 Years Old', 'The youngest mother on record was a five-year-old Peruvian girl.', 0, TRUE ,  3311,  0,  0,  0,  11),
    (group_id, 'http://www.snopes.com/pregnant/youngestmother.asp', TRUE , image_id, 'World’s Youngest Mother — 5 Years Old', 'The youngest mother on record was a five-year-old Peruvian girl.', +1, FALSE ,  88601,  0,  0,  0,  0),
    (group_id, 'http://www.snopes.com/pregnant/youngestmother.asp', TRUE , image_id, 'World’s Youngest Mother — 5 Years Old', 'The youngest mother on record was a five-year-old Peruvian girl.', -1, FALSE ,  88601,  0,  0,  0,  0);

  INSERT INTO image (data, "contentType") VALUES ( http_get('http://lorempixel.com/400/200/'), 'image/jpeg') RETURNING id INTO image_id;
  INSERT INTO "articleGroup" (id) VALUES (DEFAULT) RETURNING id INTO group_id;
  INSERT INTO article ("fkGroup", "sourceUrl", "articleIsTrue", "fkScreenshot", heading, summary, "metricsAlteration", "metricsTrue", "fbShares", "fbLikes", "fbComments", "twRetweets", "twLikes") VALUES
    (group_id, 'https://www.newscientist.com/article/2129185-female-dragonflies-fake-sudden-death-to-avoid-male-advances/', TRUE , image_id, 'Female dragonflies fake sudden death to avoid male advances', 'Female dragonflies use an extreme tactic to get rid of unwanted suitors: they drop out the sky and then pretend to be dead.', 0, TRUE ,  241973,  0,  0,  772,  1100),
    (group_id, 'https://www.newscientist.com/article/2129185-female-dragonflies-fake-sudden-death-to-avoid-male-advances/', TRUE , image_id, 'Female dragonflies fake sudden death to avoid male advances', 'Female dragonflies use an extreme tactic to get rid of unwanted suitors: they drop out the sky and then pretend to be dead.', +1, FALSE ,  88601,  0,  0,  0,  0),
    (group_id, 'https://www.newscientist.com/article/2129185-female-dragonflies-fake-sudden-death-to-avoid-male-advances/', TRUE , image_id, 'Female dragonflies fake sudden death to avoid male advances', 'Female dragonflies use an extreme tactic to get rid of unwanted suitors: they drop out the sky and then pretend to be dead.', -1, FALSE ,  88601,  0,  0,  0,  0);

  INSERT INTO image (data, "contentType") VALUES ( http_get('http://lorempixel.com/400/200/'), 'image/jpeg') RETURNING id INTO image_id;
  INSERT INTO "articleGroup" (id) VALUES (DEFAULT) RETURNING id INTO group_id;
  INSERT INTO article ("fkGroup", "sourceUrl", "articleIsTrue", "fkScreenshot", heading, summary, "metricsAlteration", "metricsTrue", "fbShares", "fbLikes", "fbComments", "twRetweets", "twLikes") VALUES
    (group_id, 'http://www.independent.co.uk/environment/prince-charles-squirrels-nutella-sterilise-plans-backs-grey-red-a7597481.html', TRUE , image_id, 'Prince Charles backs plan to use Nutella as bait to sterilise grey squirrels', 'Prince Charles has backed a government plan to sterilise grey squirrels using traps filled with Nutella, in a bid to protect their smaller red cousins.', 0, TRUE ,  616,  0,  0,  25,  120),
    (group_id, 'http://www.independent.co.uk/environment/prince-charles-squirrels-nutella-sterilise-plans-backs-grey-red-a7597481.html', TRUE , image_id, 'Prince Charles backs plan to use Nutella as bait to sterilise grey squirrels', 'Prince Charles has backed a government plan to sterilise grey squirrels using traps filled with Nutella, in a bid to protect their smaller red cousins.', +1, FALSE ,  88601,  0,  0,  0,  0),
    (group_id, 'http://www.independent.co.uk/environment/prince-charles-squirrels-nutella-sterilise-plans-backs-grey-red-a7597481.html', TRUE , image_id, 'Prince Charles backs plan to use Nutella as bait to sterilise grey squirrels', 'Prince Charles has backed a government plan to sterilise grey squirrels using traps filled with Nutella, in a bid to protect their smaller red cousins.', -1, FALSE ,  88601,  0,  0,  0,  0);

  INSERT INTO image (data, "contentType") VALUES ( http_get('http://lorempixel.com/400/200/'), 'image/jpeg') RETURNING id INTO image_id;
  INSERT INTO "articleGroup" (id) VALUES (DEFAULT) RETURNING id INTO group_id;
  INSERT INTO article ("fkGroup", "sourceUrl", "articleIsTrue", "fkScreenshot", heading, summary, "metricsAlteration", "metricsTrue", "fbShares", "fbLikes", "fbComments", "twRetweets", "twLikes") VALUES
    (group_id, 'https://www.baysidestarnews.com.au/news/judge-praises-drug-dealer-its-good-business-model/3171155', TRUE , image_id, 'Judge praises drug dealer for good business model', 'A Queensland Supreme Court judge has praised a drug dealer for his savvy business skills in running a methamphetamine operation. Justice Ann Lyons yesterday told Brodie Gary Satterley that it obviously wasnt the best business, but its a good business model.', 0, TRUE ,  616,  0,  0,  25,  120),
    (group_id, 'https://www.baysidestarnews.com.au/news/judge-praises-drug-dealer-its-good-business-model/3171155', TRUE , image_id, 'Judge praises drug dealer for good business model', 'A Queensland Supreme Court judge has praised a drug dealer for his savvy business skills in running a methamphetamine operation. Justice Ann Lyons yesterday told Brodie Gary Satterley that it obviously wasnt the best business, but its a good business model.', +1, FALSE ,  88601,  0,  0,  0,  0),
    (group_id, 'https://www.baysidestarnews.com.au/news/judge-praises-drug-dealer-its-good-business-model/3171155', TRUE , image_id, 'Judge praises drug dealer for good business model', 'A Queensland Supreme Court judge has praised a drug dealer for his savvy business skills in running a methamphetamine operation. Justice Ann Lyons yesterday told Brodie Gary Satterley that it obviously wasnt the best business, but its a good business model.', -1, FALSE ,  88601,  0,  0,  0,  0);

  INSERT INTO image (data, "contentType") VALUES ( http_get('http://lorempixel.com/400/200/'), 'image/jpeg') RETURNING id INTO image_id;
  INSERT INTO "articleGroup" (id) VALUES (DEFAULT) RETURNING id INTO group_id;
  INSERT INTO article ("fkGroup", "sourceUrl", "articleIsTrue", "fkScreenshot", heading, summary, "metricsAlteration", "metricsTrue", "fbShares", "fbLikes", "fbComments", "twRetweets", "twLikes") VALUES
    (group_id, 'https://ourworldindata.org/war-and-peace', TRUE , image_id, 'We are living in the most peaceful time in our species existence', 'Data shows that we are currently living in the most peaceful time in our species’ existence.', 0, TRUE ,  884,  0,  0,  25,  406),
    (group_id, 'https://ourworldindata.org/war-and-peace', TRUE , image_id, 'We are living in the most peaceful time in our species existence', 'Data shows that we are currently living in the most peaceful time in our species’ existence.', +1, FALSE ,  88601,  0,  0,  0,  0),
    (group_id, 'https://ourworldindata.org/war-and-peace', TRUE , image_id, 'We are living in the most peaceful time in our species existence', 'Data shows that we are currently living in the most peaceful time in our species’ existence.', -1, FALSE ,  88601,  0,  0,  0,  0);

  INSERT INTO image (data, "contentType") VALUES ( http_get('http://lorempixel.com/400/200/'), 'image/jpeg') RETURNING id INTO image_id;
  INSERT INTO "articleGroup" (id) VALUES (DEFAULT) RETURNING id INTO group_id;
  INSERT INTO article ("fkGroup", "sourceUrl", "articleIsTrue", "fkScreenshot", heading, summary, "metricsAlteration", "metricsTrue", "fbShares", "fbLikes", "fbComments", "twRetweets", "twLikes") VALUES
    (group_id, 'http://www.spiegel.de/wissenschaft/mensch/kannibalismus-im-kaloriencheck-naehrwerte-von-mensch-und-tier-a-1141957.html', TRUE , image_id, 'Nährwert von Menschenfleisch: Kannibalismus zahlt sich nicht aus', 'In der Steinzeit sollen hier und da Kannibalen am Werk gewesen sein, glauben Archäologen. Doch wie nahrhaft war ein Urmensch überhaupt? Ein Forscher hat nun eine makabere Kalorienrechnung aufgemacht.', 0, TRUE ,  216,  0,  0,  4,  40),
    (group_id, 'http://www.spiegel.de/wissenschaft/mensch/kannibalismus-im-kaloriencheck-naehrwerte-von-mensch-und-tier-a-1141957.html', TRUE , image_id, 'Nährwert von Menschenfleisch: Kannibalismus zahlt sich nicht aus', 'In der Steinzeit sollen hier und da Kannibalen am Werk gewesen sein, glauben Archäologen. Doch wie nahrhaft war ein Urmensch überhaupt? Ein Forscher hat nun eine makabere Kalorienrechnung aufgemacht.', +1, FALSE ,  88601,  0,  0,  0,  0),
    (group_id, 'http://www.spiegel.de/wissenschaft/mensch/kannibalismus-im-kaloriencheck-naehrwerte-von-mensch-und-tier-a-1141957.html', TRUE , image_id, 'Nährwert von Menschenfleisch: Kannibalismus zahlt sich nicht aus', 'In der Steinzeit sollen hier und da Kannibalen am Werk gewesen sein, glauben Archäologen. Doch wie nahrhaft war ein Urmensch überhaupt? Ein Forscher hat nun eine makabere Kalorienrechnung aufgemacht.', -1, FALSE ,  88601,  0,  0,  0,  0);

  INSERT INTO image (data, "contentType") VALUES ( http_get('http://lorempixel.com/400/200/'), 'image/jpeg') RETURNING id INTO image_id;
  INSERT INTO "articleGroup" (id) VALUES (DEFAULT) RETURNING id INTO group_id;
  INSERT INTO article ("fkGroup", "sourceUrl", "articleIsTrue", "fkScreenshot", heading, summary, "metricsAlteration", "metricsTrue", "fbShares", "fbLikes", "fbComments", "twRetweets", "twLikes") VALUES
    (group_id, 'https://consumerist.com/2017/02/08/factory-that-made-samsung-galaxy-note-7-batteries-catches-fire-yes-really', TRUE , image_id, 'Factory That Made Samsung Galaxy Note 7 Batteries Catches Fire (Yes, Really)', 'A factory in China that manufactured batteries for the now-defunct Samsung Galaxy Note 7 line of phones — all recalled due to their propensity for the batteries to burst into flame — itself suffered a fire this morning.', 0, TRUE ,  1874,  0,  0,  0,  43),
    (group_id, 'https://consumerist.com/2017/02/08/factory-that-made-samsung-galaxy-note-7-batteries-catches-fire-yes-really', TRUE , image_id, 'Factory That Made Samsung Galaxy Note 7 Batteries Catches Fire (Yes, Really)', 'A factory in China that manufactured batteries for the now-defunct Samsung Galaxy Note 7 line of phones — all recalled due to their propensity for the batteries to burst into flame — itself suffered a fire this morning.', +1, FALSE ,  88601,  0,  0,  0,  0),
    (group_id, 'https://consumerist.com/2017/02/08/factory-that-made-samsung-galaxy-note-7-batteries-catches-fire-yes-really', TRUE , image_id, 'Factory That Made Samsung Galaxy Note 7 Batteries Catches Fire (Yes, Really)', 'A factory in China that manufactured batteries for the now-defunct Samsung Galaxy Note 7 line of phones — all recalled due to their propensity for the batteries to burst into flame — itself suffered a fire this morning.', -1, FALSE ,  88601,  0,  0,  0,  0);

  INSERT INTO image (data, "contentType") VALUES ( http_get('http://lorempixel.com/400/200/'), 'image/jpeg') RETURNING id INTO image_id;
  INSERT INTO "articleGroup" (id) VALUES (DEFAULT) RETURNING id INTO group_id;
  INSERT INTO article ("fkGroup", "sourceUrl", "articleIsTrue", "fkScreenshot", heading, summary, "metricsAlteration", "metricsTrue", "fbShares", "fbLikes", "fbComments", "twRetweets", "twLikes") VALUES
    (group_id, 'https://kurier.at/leben/hater-dating-app-fuer-menschen-die-dieselben-dinge-hassen/244.610.244', TRUE , image_id, 'Dating-App für Menschen, die dieselben Dinge hassen', 'Nach Bumble, Whispar und 3nder kommt jetzt Hater, eine Dating-App à la Tinder für Menschen, die dieselben Dinge verabscheuen.', 0, TRUE ,  8,  0,  0,  0,  0),
    (group_id, 'https://kurier.at/leben/hater-dating-app-fuer-menschen-die-dieselben-dinge-hassen/244.610.244', TRUE , image_id, 'Dating-App für Menschen, die dieselben Dinge hassen', 'Nach Bumble, Whispar und 3nder kommt jetzt Hater, eine Dating-App à la Tinder für Menschen, die dieselben Dinge verabscheuen.', +1, FALSE ,  88601,  0,  0,  0,  0),
    (group_id, 'https://kurier.at/leben/hater-dating-app-fuer-menschen-die-dieselben-dinge-hassen/244.610.244', TRUE , image_id, 'Dating-App für Menschen, die dieselben Dinge hassen', 'Nach Bumble, Whispar und 3nder kommt jetzt Hater, eine Dating-App à la Tinder für Menschen, die dieselben Dinge verabscheuen.', -1, FALSE ,  88601,  0,  0,  0,  0);

  INSERT INTO image (data, "contentType") VALUES ( http_get('http://lorempixel.com/400/200/'), 'image/jpeg') RETURNING id INTO image_id;
  INSERT INTO "articleGroup" (id) VALUES (DEFAULT) RETURNING id INTO group_id;
  INSERT INTO article ("fkGroup", "sourceUrl", "articleIsTrue", "fkScreenshot", heading, summary, "metricsAlteration", "metricsTrue", "fbShares", "fbLikes", "fbComments", "twRetweets", "twLikes") VALUES
    (group_id, 'http://www.taz.de/Kirche-beim-Christopher-Street-Day/!5423867', FALSE , image_id, 'Kondome mit Luthers Segen', 'Beim Berliner CSD wird die Evangelische Kirche erstmals mit einem Partywagen dabei sein. Gleitgel und Kondome sollen geworfen werden.', 0, TRUE ,  1562,  0,  0,  1,  6),
    (group_id, 'http://www.taz.de/Kirche-beim-Christopher-Street-Day/!5423867', FALSE , image_id, 'Kondome mit Luthers Segen', 'Beim Berliner CSD wird die Evangelische Kirche erstmals mit einem Partywagen dabei sein. Gleitgel und Kondome sollen geworfen werden.', +1, FALSE ,  88601,  0,  0,  0,  0),
    (group_id, 'http://www.taz.de/Kirche-beim-Christopher-Street-Day/!5423867', FALSE , image_id, 'Kondome mit Luthers Segen', 'Beim Berliner CSD wird die Evangelische Kirche erstmals mit einem Partywagen dabei sein. Gleitgel und Kondome sollen geworfen werden.', -1, FALSE ,  88601,  0,  0,  0,  0);

  INSERT INTO image (data, "contentType") VALUES ( http_get('http://lorempixel.com/400/200/'), 'image/jpeg') RETURNING id INTO image_id;
  INSERT INTO "articleGroup" (id) VALUES (DEFAULT) RETURNING id INTO group_id;
  INSERT INTO article ("fkGroup", "sourceUrl", "articleIsTrue", "fkScreenshot", heading, summary, "metricsAlteration", "metricsTrue", "fbShares", "fbLikes", "fbComments", "twRetweets", "twLikes") VALUES
    (group_id, 'votum24.votum1.de/de/politik/deutsche-steuerzahler-blechen-auch-noch-fuer-fuehrerscheinerwerb-durch-migranten', FALSE , image_id, 'Führerschein für Flüchtlinge kostenlos', 'Die Bundesvereinigung der Fahrlehrerverbände (BVF) verzeichnet einen Ansturm von Asylbewerbern auf Fahrschulen. Der Grund für diesen Ansturm lässt sich leicht erklären. Die Kosten der Fahrausbildung übernimmt das Jobcenter.', 0, TRUE ,  77814,  0,  0,  0,  214),
    (group_id, 'votum24.votum1.de/de/politik/deutsche-steuerzahler-blechen-auch-noch-fuer-fuehrerscheinerwerb-durch-migranten', FALSE , image_id, 'Führerschein für Flüchtlinge kostenlos', 'Die Bundesvereinigung der Fahrlehrerverbände (BVF) verzeichnet einen Ansturm von Asylbewerbern auf Fahrschulen. Der Grund für diesen Ansturm lässt sich leicht erklären. Die Kosten der Fahrausbildung übernimmt das Jobcenter.', +1, FALSE ,  88601,  0,  0,  0,  0),
    (group_id, 'votum24.votum1.de/de/politik/deutsche-steuerzahler-blechen-auch-noch-fuer-fuehrerscheinerwerb-durch-migranten', FALSE , image_id, 'Führerschein für Flüchtlinge kostenlos', 'Die Bundesvereinigung der Fahrlehrerverbände (BVF) verzeichnet einen Ansturm von Asylbewerbern auf Fahrschulen. Der Grund für diesen Ansturm lässt sich leicht erklären. Die Kosten der Fahrausbildung übernimmt das Jobcenter.', -1, FALSE ,  88601,  0,  0,  0,  0);

  INSERT INTO image (data, "contentType") VALUES ( http_get('http://lorempixel.com/400/200/'), 'image/jpeg') RETURNING id INTO image_id;
  INSERT INTO "articleGroup" (id) VALUES (DEFAULT) RETURNING id INTO group_id;
  INSERT INTO article ("fkGroup", "sourceUrl", "articleIsTrue", "fkScreenshot", heading, summary, "metricsAlteration", "metricsTrue", "fbShares", "fbLikes", "fbComments", "twRetweets", "twLikes") VALUES
    (group_id, 'http://www.das-unbekannte.de/wenn-man-grillen-geraeusche-verlangsamt-entdeckt-man-etwas-unerwartetes/', FALSE , image_id, 'Verlangsamtes Grillenzirpen klingt wie ein menschlicher Chor', 'Jim Wilson, ein Komponist, machte zufällig eine sehr erstaunliche Entdeckung. Er nahm das Zirpen von Grillen auf, verlangsamte die Aufnahme anschließend und konnte seinen Ohren nicht trauen. Die Aufnahme hörte sich an wie ein Chor aus menschlichen Stimmen.', 0, TRUE ,  25095,  0,  0,  0,  0),
    (group_id, 'http://www.das-unbekannte.de/wenn-man-grillen-geraeusche-verlangsamt-entdeckt-man-etwas-unerwartetes/', FALSE , image_id, 'Verlangsamtes Grillenzirpen klingt wie ein menschlicher Chor', 'Jim Wilson, ein Komponist, machte zufällig eine sehr erstaunliche Entdeckung. Er nahm das Zirpen von Grillen auf, verlangsamte die Aufnahme anschließend und konnte seinen Ohren nicht trauen. Die Aufnahme hörte sich an wie ein Chor aus menschlichen Stimmen.', +1, FALSE ,  88601,  0,  0,  0,  0),
    (group_id, 'http://www.das-unbekannte.de/wenn-man-grillen-geraeusche-verlangsamt-entdeckt-man-etwas-unerwartetes/', FALSE , image_id, 'Verlangsamtes Grillenzirpen klingt wie ein menschlicher Chor', 'Jim Wilson, ein Komponist, machte zufällig eine sehr erstaunliche Entdeckung. Er nahm das Zirpen von Grillen auf, verlangsamte die Aufnahme anschließend und konnte seinen Ohren nicht trauen. Die Aufnahme hörte sich an wie ein Chor aus menschlichen Stimmen.', -1, FALSE ,  88601,  0,  0,  0,  0);

  INSERT INTO image (data, "contentType") VALUES ( http_get('http://lorempixel.com/400/200/'), 'image/jpeg') RETURNING id INTO image_id;
  INSERT INTO "articleGroup" (id) VALUES (DEFAULT) RETURNING id INTO group_id;
  INSERT INTO article ("fkGroup", "sourceUrl", "articleIsTrue", "fkScreenshot", heading, summary, "metricsAlteration", "metricsTrue", "fbShares", "fbLikes", "fbComments", "twRetweets", "twLikes") VALUES
    (group_id, 'http://erstaunlich.at/index.php?option=com_content&view=article&id=3316%3Afreikarte-fuer-bordellbesuch-vom-sozialamt&catid=1%3Aerstaunliches&Itemid=1', FALSE , image_id, 'Freikarte für Bordellbesuch vom Sozialamt', 'Wie uns aus einer sehr zuverlässigen  Quelle mitgeteilt wurde,  soll das Sozialamt Graz Gutscheine  für Bordellbesuche vergeben.  Diese gelten allerdings nicht in den Hauptstoßzeiten.', 0, TRUE ,  39,  0,  0,  0,  0),
    (group_id, 'http://erstaunlich.at/index.php?option=com_content&view=article&id=3316%3Afreikarte-fuer-bordellbesuch-vom-sozialamt&catid=1%3Aerstaunliches&Itemid=1', FALSE , image_id, 'Freikarte für Bordellbesuch vom Sozialamt', 'Wie uns aus einer sehr zuverlässigen  Quelle mitgeteilt wurde,  soll das Sozialamt Graz Gutscheine  für Bordellbesuche vergeben.  Diese gelten allerdings nicht in den Hauptstoßzeiten.', +1, FALSE ,  88601,  0,  0,  0,  0),
    (group_id, 'http://erstaunlich.at/index.php?option=com_content&view=article&id=3316%3Afreikarte-fuer-bordellbesuch-vom-sozialamt&catid=1%3Aerstaunliches&Itemid=1', FALSE , image_id, 'Freikarte für Bordellbesuch vom Sozialamt', 'Wie uns aus einer sehr zuverlässigen  Quelle mitgeteilt wurde,  soll das Sozialamt Graz Gutscheine  für Bordellbesuche vergeben.  Diese gelten allerdings nicht in den Hauptstoßzeiten.', -1, FALSE ,  88601,  0,  0,  0,  0);

  INSERT INTO image (data, "contentType") VALUES ( http_get('http://lorempixel.com/400/200/'), 'image/jpeg') RETURNING id INTO image_id;
  INSERT INTO "articleGroup" (id) VALUES (DEFAULT) RETURNING id INTO group_id;
  INSERT INTO article ("fkGroup", "sourceUrl", "articleIsTrue", "fkScreenshot", heading, summary, "metricsAlteration", "metricsTrue", "fbShares", "fbLikes", "fbComments", "twRetweets", "twLikes") VALUES
    (group_id, 'https://www.facebook.com/photo.php?fbid=1816655728601073', FALSE , image_id, 'PIN am Bankomat rückwärts eintippen löst Polizeinotruf aus', 'Werden Sie während eines Raubüberfalles dazu gezwungen, Geld vom Bankomaten abzuheben, geben Sie die PIN rückwärts (z.B. 4321 statt 1234) ein. Der Automat alarmiert sofort die Polizei. Jeder Bankomat hat diese Funktion.', 0, TRUE ,  1729886,  37772,  0,  0,  0),
    (group_id, 'https://www.facebook.com/photo.php?fbid=1816655728601073', FALSE , image_id, 'PIN am Bankomat rückwärts eintippen löst Polizeinotruf aus', 'Werden Sie während eines Raubüberfalles dazu gezwungen, Geld vom Bankomaten abzuheben, geben Sie die PIN rückwärts (z.B. 4321 statt 1234) ein. Der Automat alarmiert sofort die Polizei. Jeder Bankomat hat diese Funktion.', +1, FALSE ,  88601,  0,  0,  0,  0),
    (group_id, 'https://www.facebook.com/photo.php?fbid=1816655728601073', FALSE , image_id, 'PIN am Bankomat rückwärts eintippen löst Polizeinotruf aus', 'Werden Sie während eines Raubüberfalles dazu gezwungen, Geld vom Bankomaten abzuheben, geben Sie die PIN rückwärts (z.B. 4321 statt 1234) ein. Der Automat alarmiert sofort die Polizei. Jeder Bankomat hat diese Funktion.', -1, FALSE ,  88601,  0,  0,  0,  0);

  INSERT INTO image (data, "contentType") VALUES ( http_get('http://lorempixel.com/400/200/'), 'image/jpeg') RETURNING id INTO image_id;
  INSERT INTO "articleGroup" (id) VALUES (DEFAULT) RETURNING id INTO group_id;
  INSERT INTO article ("fkGroup", "sourceUrl", "articleIsTrue", "fkScreenshot", heading, summary, "metricsAlteration", "metricsTrue", "fbShares", "fbLikes", "fbComments", "twRetweets", "twLikes") VALUES
    (group_id, 'www.krone.at/oesterreich/mehrere-waffen-in-versteck-auf-donauinsel-gefunden-vor-donauinselfest-story-575388', FALSE , image_id, 'Mehrere Waffen in Versteck auf Donauinsel gefunden', 'Nur wenige Stunden vor Beginn des 34. Donauinselfest gibt es Aufregung um einen brisanten Fund: In einem Versteck auf der Donauinsel lagen zwei Maschinenpistolen und eine Faustfeuerwaffe, wie die Krone erfuhr. Ob es einen Zusammenhang mit der Riesenveranstaltung gibt, ist noch nicht geklärt.', 0, TRUE ,  145,  0,  0,  0,  0),
    (group_id, 'www.krone.at/oesterreich/mehrere-waffen-in-versteck-auf-donauinsel-gefunden-vor-donauinselfest-story-575388', FALSE , image_id, 'Mehrere Waffen in Versteck auf Donauinsel gefunden', 'Nur wenige Stunden vor Beginn des 34. Donauinselfest gibt es Aufregung um einen brisanten Fund: In einem Versteck auf der Donauinsel lagen zwei Maschinenpistolen und eine Faustfeuerwaffe, wie die Krone erfuhr. Ob es einen Zusammenhang mit der Riesenveranstaltung gibt, ist noch nicht geklärt.', +1, FALSE ,  88601,  0,  0,  0,  0),
    (group_id, 'www.krone.at/oesterreich/mehrere-waffen-in-versteck-auf-donauinsel-gefunden-vor-donauinselfest-story-575388', FALSE , image_id, 'Mehrere Waffen in Versteck auf Donauinsel gefunden', 'Nur wenige Stunden vor Beginn des 34. Donauinselfest gibt es Aufregung um einen brisanten Fund: In einem Versteck auf der Donauinsel lagen zwei Maschinenpistolen und eine Faustfeuerwaffe, wie die Krone erfuhr. Ob es einen Zusammenhang mit der Riesenveranstaltung gibt, ist noch nicht geklärt.', -1, FALSE ,  88601,  0,  0,  0,  0);

  INSERT INTO image (data, "contentType") VALUES ( http_get('http://lorempixel.com/400/200/'), 'image/jpeg') RETURNING id INTO image_id;
  INSERT INTO "articleGroup" (id) VALUES (DEFAULT) RETURNING id INTO group_id;
  INSERT INTO article ("fkGroup", "sourceUrl", "articleIsTrue", "fkScreenshot", heading, summary, "metricsAlteration", "metricsTrue", "fbShares", "fbLikes", "fbComments", "twRetweets", "twLikes") VALUES
    (group_id, 'http://www.heute.at/oesterreich/oberoesterreich/story/Frau-lie--sich-Zelle-von-Hund-in-Eizelle-einsetzen-59767881', TRUE , image_id, 'Frau ließ sich Zelle von Hund einsetzen', 'Im Rahmen eines Kunstprojekts wurde eine Eizelle der Künstlerin von Experten in einem Labor "entkernt" und darin eine Körperzelle ihres Hundes einpflanzt.', 0, TRUE ,  201,  0,  0,  2,  46),
    (group_id, 'http://www.heute.at/oesterreich/oberoesterreich/story/Frau-lie--sich-Zelle-von-Hund-in-Eizelle-einsetzen-59767881', TRUE , image_id, 'Frau ließ sich Zelle von Hund einsetzen', 'Im Rahmen eines Kunstprojekts wurde eine Eizelle der Künstlerin von Experten in einem Labor "entkernt" und darin eine Körperzelle ihres Hundes einpflanzt.', +1, FALSE ,  88601,  0,  0,  0,  0),
    (group_id, 'http://www.heute.at/oesterreich/oberoesterreich/story/Frau-lie--sich-Zelle-von-Hund-in-Eizelle-einsetzen-59767881', TRUE , image_id, 'Frau ließ sich Zelle von Hund einsetzen', 'Im Rahmen eines Kunstprojekts wurde eine Eizelle der Künstlerin von Experten in einem Labor "entkernt" und darin eine Körperzelle ihres Hundes einpflanzt.', -1, FALSE ,  88601,  0,  0,  0,  0);

  INSERT INTO image (data, "contentType") VALUES ( http_get('http://lorempixel.com/400/200/'), 'image/jpeg') RETURNING id INTO image_id;
  INSERT INTO "articleGroup" (id) VALUES (DEFAULT) RETURNING id INTO group_id;
  INSERT INTO article ("fkGroup", "sourceUrl", "articleIsTrue", "fkScreenshot", heading, summary, "metricsAlteration", "metricsTrue", "fbShares", "fbLikes", "fbComments", "twRetweets", "twLikes") VALUES
    (group_id, 'https://netzfrauen.org/2017/06/09/plastik-reis/', FALSE , image_id, 'Gefälschter Reis aus Plastik', 'August 2016 veröffentlichte die Europäische Behörde für Lebensmittelsicherheit (EFSA) ihren Jahresbericht über aufkommende Risiken. Unter den Top 10 Risiken: Plastik-Reis.', 0, TRUE ,  5629,  0,  0,  4,  4),
    (group_id, 'https://netzfrauen.org/2017/06/09/plastik-reis/', FALSE , image_id, 'Gefälschter Reis aus Plastik', 'August 2016 veröffentlichte die Europäische Behörde für Lebensmittelsicherheit (EFSA) ihren Jahresbericht über aufkommende Risiken. Unter den Top 10 Risiken: Plastik-Reis.', +1, FALSE ,  88601,  0,  0,  0,  0),
    (group_id, 'https://netzfrauen.org/2017/06/09/plastik-reis/', FALSE , image_id, 'Gefälschter Reis aus Plastik', 'August 2016 veröffentlichte die Europäische Behörde für Lebensmittelsicherheit (EFSA) ihren Jahresbericht über aufkommende Risiken. Unter den Top 10 Risiken: Plastik-Reis.', -1, FALSE ,  88601,  0,  0,  0,  0);

  INSERT INTO image (data, "contentType") VALUES ( http_get('http://lorempixel.com/400/200/'), 'image/jpeg') RETURNING id INTO image_id;
  INSERT INTO "articleGroup" (id) VALUES (DEFAULT) RETURNING id INTO group_id;
  INSERT INTO article ("fkGroup", "sourceUrl", "articleIsTrue", "fkScreenshot", heading, summary, "metricsAlteration", "metricsTrue", "fbShares", "fbLikes", "fbComments", "twRetweets", "twLikes") VALUES
    (group_id, 'http://worldnewsdailyreport.com/7-year-old-girl-receives-breast-implants-for-christmas/', FALSE , image_id, '7-Jährige bekam Brustimplantate zu Weihnachten geschenkt', 'Juliet Manson aus Glendale, Kalifornien bekam dieses Jahr zu Weihnachten von ihrer Mutter ein ganz besonderes Geschenk: eine Reise nach China, um sich einer Brustvergrößerung zu unterziehen.', 0, TRUE ,  39358,  0,  0,  0,  13),
    (group_id, 'http://worldnewsdailyreport.com/7-year-old-girl-receives-breast-implants-for-christmas/', FALSE , image_id, '7-Jährige bekam Brustimplantate zu Weihnachten geschenkt', 'Juliet Manson aus Glendale, Kalifornien bekam dieses Jahr zu Weihnachten von ihrer Mutter ein ganz besonderes Geschenk: eine Reise nach China, um sich einer Brustvergrößerung zu unterziehen.', +1, FALSE ,  88601,  0,  0,  0,  0),
    (group_id, 'http://worldnewsdailyreport.com/7-year-old-girl-receives-breast-implants-for-christmas/', FALSE , image_id, '7-Jährige bekam Brustimplantate zu Weihnachten geschenkt', 'Juliet Manson aus Glendale, Kalifornien bekam dieses Jahr zu Weihnachten von ihrer Mutter ein ganz besonderes Geschenk: eine Reise nach China, um sich einer Brustvergrößerung zu unterziehen.', -1, FALSE ,  88601,  0,  0,  0,  0);

  INSERT INTO image (data, "contentType") VALUES ( http_get('http://lorempixel.com/400/200/'), 'image/jpeg') RETURNING id INTO image_id;
  INSERT INTO "articleGroup" (id) VALUES (DEFAULT) RETURNING id INTO group_id;
  INSERT INTO article ("fkGroup", "sourceUrl", "articleIsTrue", "fkScreenshot", heading, summary, "metricsAlteration", "metricsTrue", "fbShares", "fbLikes", "fbComments", "twRetweets", "twLikes") VALUES
    (group_id, 'http://haynoticia.es/mujer-lleva-28-anos-haciendose-pasar-ciega-no-saludar-la-gente3333/', FALSE , image_id, 'Frau täuschte Blindheit vor - 28 Jahre lang', '57-Jährige bestätigte vor Kurzem, einen von ihren Nachbarn bereits länger gehegten Verdacht: sie habe ihre Blindheit nur vorgetäuscht. So habe sie Bekannte auf der Straße nicht mehr grüßen müssen, behauptet Carmen Jimenez', 0, TRUE ,  70173,  0,  0,  0,  0),
    (group_id, 'http://haynoticia.es/mujer-lleva-28-anos-haciendose-pasar-ciega-no-saludar-la-gente3333/', FALSE , image_id, 'Frau täuschte Blindheit vor - 28 Jahre lang', '57-Jährige bestätigte vor Kurzem, einen von ihren Nachbarn bereits länger gehegten Verdacht: sie habe ihre Blindheit nur vorgetäuscht. So habe sie Bekannte auf der Straße nicht mehr grüßen müssen, behauptet Carmen Jimenez', +1, FALSE ,  88601,  0,  0,  0,  0),
    (group_id, 'http://haynoticia.es/mujer-lleva-28-anos-haciendose-pasar-ciega-no-saludar-la-gente3333/', FALSE , image_id, 'Frau täuschte Blindheit vor - 28 Jahre lang', '57-Jährige bestätigte vor Kurzem, einen von ihren Nachbarn bereits länger gehegten Verdacht: sie habe ihre Blindheit nur vorgetäuscht. So habe sie Bekannte auf der Straße nicht mehr grüßen müssen, behauptet Carmen Jimenez', -1, FALSE ,  88601,  0,  0,  0,  0);

  INSERT INTO image (data, "contentType") VALUES ( http_get('http://lorempixel.com/400/200/'), 'image/jpeg') RETURNING id INTO image_id;
  INSERT INTO "articleGroup" (id) VALUES (DEFAULT) RETURNING id INTO group_id;
  INSERT INTO article ("fkGroup", "sourceUrl", "articleIsTrue", "fkScreenshot", heading, summary, "metricsAlteration", "metricsTrue", "fbShares", "fbLikes", "fbComments", "twRetweets", "twLikes") VALUES
    (group_id, 'https://www.waz.de/politik/afd-mann-raet-frauenverbrennung-um-klima-zu-retten-id210539979.html', FALSE , image_id, 'AfD-Politiker Podeswa fordert Frauenverbrennungen gegen Klimawandel', 'AfD-Politiker Rainer Podeswa meint zu wissen, wie man den Klimawandel stoppen kann. Seine „Empfehlung“ im Landtag, sich im Kampf gegen den Klimawandel am „Hexenhammer“ zu orientieren, hatte für Empörung gesorgt.', 0, TRUE ,  591,  0,  0,  0,  0),
    (group_id, 'https://www.waz.de/politik/afd-mann-raet-frauenverbrennung-um-klima-zu-retten-id210539979.html', FALSE , image_id, 'AfD-Politiker Podeswa fordert Frauenverbrennungen gegen Klimawandel', 'AfD-Politiker Rainer Podeswa meint zu wissen, wie man den Klimawandel stoppen kann. Seine „Empfehlung“ im Landtag, sich im Kampf gegen den Klimawandel am „Hexenhammer“ zu orientieren, hatte für Empörung gesorgt.', +1, FALSE ,  88601,  0,  0,  0,  0),
    (group_id, 'https://www.waz.de/politik/afd-mann-raet-frauenverbrennung-um-klima-zu-retten-id210539979.html', FALSE , image_id, 'AfD-Politiker Podeswa fordert Frauenverbrennungen gegen Klimawandel', 'AfD-Politiker Rainer Podeswa meint zu wissen, wie man den Klimawandel stoppen kann. Seine „Empfehlung“ im Landtag, sich im Kampf gegen den Klimawandel am „Hexenhammer“ zu orientieren, hatte für Empörung gesorgt.', -1, FALSE ,  88601,  0,  0,  0,  0);

END
$$;
