SET SEARCH_PATH TO db, public;

-- insert articles
DO $$
DECLARE
  image_id INTEGER;
  group_id INTEGER;
BEGIN

  -- insert a new image and store id in `image_id`
  INSERT INTO image (data, "contentType") VALUES ( http_get('https://cdn.pixabay.com/photo/2017/01/30/15/02/man-2021062_960_720.jpg'), 'image/jpeg') RETURNING id INTO image_id;

  -- create a new articleGroup and store id in `group_id`
  INSERT INTO "articleGroup" (id) VALUES (DEFAULT) RETURNING id INTO group_id;

  -- insert articles
  INSERT INTO article ("fkGroup", "sourceUrl", "articleIsTrue", "fkScreenshot", heading, summary, "metricsAlteration", "metricsTrue", "fbShares", "fbLikes", "fbComments", "twRetweets", "twLikes") VALUES
    (group_id, 'https://www.welt.de/vermischtes/article1480019/Unglaublich-aber-wahr-Der-schwangere-indische-Mann.html', TRUE  , image_id, 'Der schwangere indische Mann', 'Der 36-jährige Sanju Bhagat lässt sich mit einem ungewöhnlich dicken Bauch in ein indisches Krankenhaus einliefern, doch als die Ärzte ihn aufschneiden, überkommt sie der blanke Horror: In seinem Körper befindet sich ein zweiter Mensch.',  0, TRUE  , NULL, NULL, NULL, NULL, NULL),
    (group_id, 'https://www.welt.de/vermischtes/article1480019/Unglaublich-aber-wahr-Der-schwangere-indische-Mann.html', TRUE  , image_id, 'Der schwangere indische Mann', 'Der 36-jährige Sanju Bhagat lässt sich mit einem ungewöhnlich dicken Bauch in ein indisches Krankenhaus einliefern, doch als die Ärzte ihn aufschneiden, überkommt sie der blanke Horror: In seinem Körper befindet sich ein zweiter Mensch.',  +1, FALSE  , 6741, 28433, 902, 32199, 39556),
    (group_id, 'https://www.welt.de/vermischtes/article1480019/Unglaublich-aber-wahr-Der-schwangere-indische-Mann.html', TRUE  , image_id, 'Der schwangere indische Mann', 'Der 36-jährige Sanju Bhagat lässt sich mit einem ungewöhnlich dicken Bauch in ein indisches Krankenhaus einliefern, doch als die Ärzte ihn aufschneiden, überkommt sie der blanke Horror: In seinem Körper befindet sich ein zweiter Mensch.',  -1, FALSE  , 0, 1, 6, 1, 1);

  INSERT INTO image (data, "contentType") VALUES ( http_get('https://cdn.pixabay.com/photo/2014/09/17/21/58/elections-450164_960_720.jpg'), 'image/jpeg') RETURNING id INTO image_id;
  INSERT INTO "articleGroup" (id) VALUES (DEFAULT) RETURNING id INTO group_id;
  INSERT INTO article ("fkGroup", "sourceUrl", "articleIsTrue", "fkScreenshot", heading, summary, "metricsAlteration", "metricsTrue", "fbShares", "fbLikes", "fbComments", "twRetweets", "twLikes") VALUES
    (group_id, 'http://www.politico.eu/article/romanian-election-pits-three-men-with-same-name-against-each-other-vasile-cepoi-draguseni', TRUE , image_id, '3 gleichnamige Kandidaten bei Rumänischer Wahl', 'Vasile Cepoi gegen Vasile Cepoi, Vasile Cepoi und jemanden, dessen Name nicht Vasile Cepoi lautet.', 0, TRUE , 1906, NULL, NULL, 3, 75),
        (group_id, 'http://www.politico.eu/article/romanian-election-pits-three-men-with-same-name-against-each-other-vasile-cepoi-draguseni', TRUE , image_id, '3 gleichnamige Kandidaten bei Rumänischer Wahl', 'Vasile Cepoi gegen Vasile Cepoi, Vasile Cepoi und jemanden, dessen Name nicht Vasile Cepoi lautet.', +1, FALSE , 9905, NULL, NULL, 3442, 2323),
    (group_id, 'http://www.politico.eu/article/romanian-election-pits-three-men-with-same-name-against-each-other-vasile-cepoi-draguseni', TRUE , image_id, '3 gleichnamige Kandidaten bei Rumänischer Wahl', 'Vasile Cepoi gegen Vasile Cepoi, Vasile Cepoi und jemanden, dessen Name nicht Vasile Cepoi lautet.', -1, FALSE , 9, NULL, NULL, 1, 2);

  INSERT INTO image (data, "contentType") VALUES ( http_get('https://cdn.pixabay.com/photo/2015/06/18/16/23/medical-813871_960_720.jpg'), 'image/jpeg') RETURNING id INTO image_id;
  INSERT INTO "articleGroup" (id) VALUES (DEFAULT) RETURNING id INTO group_id;
  INSERT INTO article ("fkGroup", "sourceUrl", "articleIsTrue", "fkScreenshot", heading, summary, "metricsAlteration", "metricsTrue", "fbShares", "fbLikes", "fbComments", "twRetweets", "twLikes") VALUES
    (group_id, 'http://www.bbc.com/future/story/20170315-the-invention-of-heterosexuality', TRUE , image_id, 'Die Erfindung der Heterosexualität', 'Vor 100 Jahren hatten Leute eine sehr unterschiedliche Sichtweise darauf, was es bedeutet heterosexuell zu sein. Dorlands Medizinisches Wörterbuch definiert Heterosexualität als abnormalen oder perversen Appetit auf das andere Geschlecht.', 0, TRUE ,  88621,  NULL,  NULL,  83,  3064),
        (group_id, 'http://www.bbc.com/future/story/20170315-the-invention-of-heterosexuality', TRUE , image_id, 'Die Erfindung der Heterosexualität', 'Vor 100 Jahren hatten Leute eine sehr unterschiedliche Sichtweise darauf, was es bedeutet heterosexuell zu sein. Dorlands Medizinisches Wörterbuch definiert Heterosexualität als abnormalen oder perversen Appetit auf das andere Geschlecht.', +1, FALSE ,  88621,  NULL,  NULL,  664,  3064),
    (group_id, 'http://www.bbc.com/future/story/20170315-the-invention-of-heterosexuality', TRUE , image_id, 'Die Erfindung der Heterosexualität', 'Vor 100 Jahren hatten Leute eine sehr unterschiedliche Sichtweise darauf, was es bedeutet heterosexuell zu sein. Dorlands Medizinisches Wörterbuch definiert Heterosexualität als abnormalen oder perversen Appetit auf das andere Geschlecht.', -1, FALSE ,  45,  NULL,  NULL,  1,  0);

  INSERT INTO image (data, "contentType") VALUES ( http_get('https://cdn.pixabay.com/photo/2016/11/22/22/43/beach-1851002_960_720.jpg'), 'image/jpeg') RETURNING id INTO image_id;
  INSERT INTO "articleGroup" (id) VALUES (DEFAULT) RETURNING id INTO group_id;
  INSERT INTO article ("fkGroup", "sourceUrl", "articleIsTrue", "fkScreenshot", heading, summary, "metricsAlteration", "metricsTrue", "fbShares", "fbLikes", "fbComments", "twRetweets", "twLikes") VALUES
    (group_id, 'http://www.villaitaliankitchen.com/blog/post/introducing-the-pizzakini-the-worlds-most-mouthwatering-bikini', TRUE , image_id, 'Maßgeschneiderter 10.000$ Pizza-Bikini', 'Anlässlich des Amerikanischen Tags des Bikini bringt Villa Italian Kitchen einen komplett aus Pizza gefertigten, maßgeschneiderten Bikini zum Preis von 10.000$ auf den Markt.', 0, TRUE ,  20,  NULL,  NULL,  NULL,  NULL),
        (group_id, 'http://www.villaitaliankitchen.com/blog/post/introducing-the-pizzakini-the-worlds-most-mouthwatering-bikini', TRUE , image_id, 'Maßgeschneiderter 10.000$ Pizza-Bikini', 'Anlässlich des Amerikanischen Tags des Bikini bringt Villa Italian Kitchen einen komplett aus Pizza gefertigten, maßgeschneiderten Bikini zum Preis von 10.000$ auf den Markt.', -1, FALSE ,  6,  5,  5,  0,  0),
    (group_id, 'http://www.villaitaliankitchen.com/blog/post/introducing-the-pizzakini-the-worlds-most-mouthwatering-bikini', TRUE , image_id, 'Maßgeschneiderter 10.000$ Pizza-Bikini', 'Anlässlich des Amerikanischen Tags des Bikini bringt Villa Italian Kitchen einen komplett aus Pizza gefertigten, maßgeschneiderten Bikini zum Preis von 10.000$ auf den Markt.', +1, FALSE ,  8860,  32452,  522,  9462,  9270);

  INSERT INTO image (data, "contentType") VALUES ( http_get('https://cdn.pixabay.com/photo/2016/10/08/15/37/sphodromantis-lineola-1723954_960_720.jpg'), 'image/jpeg') RETURNING id INTO image_id;
  INSERT INTO "articleGroup" (id) VALUES (DEFAULT) RETURNING id INTO group_id;
  INSERT INTO article ("fkGroup", "sourceUrl", "articleIsTrue", "fkScreenshot", heading, summary, "metricsAlteration", "metricsTrue", "fbShares", "fbLikes", "fbComments", "twRetweets", "twLikes") VALUES
    (group_id, 'http://science.orf.at/stories/2852839', TRUE , image_id, 'Gottesanbeterinnen fressen auch Vögel', 'Mit ihren kräftigen Fangbeinen können Gottesanbeterinnen neben Insekten und Spinnen auch kleine Wirbeltiere erbeuten, darunter Frösche, Eidechsen, Salamander und Schlangen. Nun berichten Zoologen, dass die Raubinsekten auch kleine Vögel jagen und fressen.', 0, TRUE ,  5,  NULL,  NULL,  NULL,  5),
        (group_id, 'http://science.orf.at/stories/2852839', TRUE , image_id, 'Gottesanbeterinnen fressen auch Vögel', 'Mit ihren kräftigen Fangbeinen können Gottesanbeterinnen neben Insekten und Spinnen auch kleine Wirbeltiere erbeuten, darunter Frösche, Eidechsen, Salamander und Schlangen. Nun berichten Zoologen, dass die Raubinsekten auch kleine Vögel jagen und fressen.', -1, FALSE ,  5,  NULL,  NULL,  NULL,  2),
    (group_id, 'http://science.orf.at/stories/2852839', TRUE , image_id, 'Gottesanbeterinnen fressen auch Vögel', 'Mit ihren kräftigen Fangbeinen können Gottesanbeterinnen neben Insekten und Spinnen auch kleine Wirbeltiere erbeuten, darunter Frösche, Eidechsen, Salamander und Schlangen. Nun berichten Zoologen, dass die Raubinsekten auch kleine Vögel jagen und fressen.', +1, FALSE ,  5013,  NULL,  NULL,  NULL,  2942);

  INSERT INTO image (data, "contentType") VALUES ( http_get('https://cdn.pixabay.com/photo/2017/06/08/16/39/kangaroo-2384072_960_720.jpg'), 'image/jpeg') RETURNING id INTO image_id;
  INSERT INTO "articleGroup" (id) VALUES (DEFAULT) RETURNING id INTO group_id;
  INSERT INTO article ("fkGroup", "sourceUrl", "articleIsTrue", "fkScreenshot", heading, summary, "metricsAlteration", "metricsTrue", "fbShares", "fbLikes", "fbComments", "twRetweets", "twLikes") VALUES
    (group_id, 'http://derstandard.at/2000060633382/Volvo-Kaengurus-lassen-selbstfahrende-Autos-verzweifeln', TRUE , image_id, 'Volvo: Kängurus lassen selbstfahrende Autos verzweifeln', 'Volvos selbstfahrende Autos haben ein Problem mit Kängurus. Die Software kann laut Kevin McCann, dem Australien-Chef der schwedischen Automarke die einzigartige Fortbewegungsart der Tiere nicht analysieren und dementsprechend reagieren. Bei Rentieren und Elchen hingegen würde das selbstfahrende Auto bereits adäquat reagieren.', 0, TRUE ,  156,  NULL,  NULL,  NULL,  7),
        (group_id, 'http://derstandard.at/2000060633382/Volvo-Kaengurus-lassen-selbstfahrende-Autos-verzweifeln', TRUE , image_id, 'Volvo: Kängurus lassen selbstfahrende Autos verzweifeln', 'Volvos selbstfahrende Autos haben ein Problem mit Kängurus. Die Software kann laut Kevin McCann, dem Australien-Chef der schwedischen Automarke die einzigartige Fortbewegungsart der Tiere nicht analysieren und dementsprechend reagieren. Bei Rentieren und Elchen hingegen würde das selbstfahrende Auto bereits adäquat reagieren.', -1, FALSE ,  1,  NULL,  NULL,  NULL, 2),
    (group_id, 'http://derstandard.at/2000060633382/Volvo-Kaengurus-lassen-selbstfahrende-Autos-verzweifeln', TRUE , image_id, 'Volvo: Kängurus lassen selbstfahrende Autos verzweifeln', 'Volvos selbstfahrende Autos haben ein Problem mit Kängurus. Die Software kann laut Kevin McCann, dem Australien-Chef der schwedischen Automarke die einzigartige Fortbewegungsart der Tiere nicht analysieren und dementsprechend reagieren. Bei Rentieren und Elchen hingegen würde das selbstfahrende Auto bereits adäquat reagieren.', +1, FALSE ,  88601,  NULL,  NULL,  NULL, 36823);

  INSERT INTO image (data, "contentType") VALUES ( http_get('https://cdn.pixabay.com/photo/2015/09/06/20/24/i-beg-your-pardon-927746_960_720.jpg'), 'image/jpeg') RETURNING id INTO image_id;
  INSERT INTO "articleGroup" (id) VALUES (DEFAULT) RETURNING id INTO group_id;
  INSERT INTO article ("fkGroup", "sourceUrl", "articleIsTrue", "fkScreenshot", heading, summary, "metricsAlteration", "metricsTrue", "fbShares", "fbLikes", "fbComments", "twRetweets", "twLikes") VALUES
    (group_id, 'http://indianexpress.com/article/india/india-news-india/assam-unique-frog-wedding-organised-to-appease-rain-god-4400839', TRUE , image_id, 'Froschhochzeit', 'Einem alten religiösen Brauch zufolge, sorgt eine Froschhochzeit für eine üppige Regenzeit. Ein weiblicher Frosch wird mit einer hölzernen Figur verheiratet, die für den hinduistischen Regengott, Indra, steht.', 0, TRUE ,  13,  NULL,  NULL,  NULL,  9),
        (group_id, 'http://indianexpress.com/article/india/india-news-india/assam-unique-frog-wedding-organised-to-appease-rain-god-4400839', TRUE , image_id, 'Froschhochzeit', 'Einem alten religiösen Brauch zufolge, sorgt eine Froschhochzeit für eine üppige Regenzeit. Ein weiblicher Frosch wird mit einer hölzernen Figur verheiratet, die für den hinduistischen Regengott, Indra, steht.', -1, FALSE ,  3,  NULL,  NULL,  NULL,  1),
    (group_id, 'http://indianexpress.com/article/india/india-news-india/assam-unique-frog-wedding-organised-to-appease-rain-god-4400839', TRUE , image_id, 'Froschhochzeit', 'Einem alten religiösen Brauch zufolge, sorgt eine Froschhochzeit für eine üppige Regenzeit. Ein weiblicher Frosch wird mit einer hölzernen Figur verheiratet, die für den hinduistischen Regengott, Indra, steht.', +1, FALSE ,  601,  NULL,  NULL,  NULL,  323);

  INSERT INTO image (data, "contentType") VALUES ( http_get('https://cdn.pixabay.com/photo/2016/06/06/21/57/tick-1440531_960_720.jpg'), 'image/jpeg') RETURNING id INTO image_id;
  INSERT INTO "articleGroup" (id) VALUES (DEFAULT) RETURNING id INTO group_id;
  INSERT INTO article ("fkGroup", "sourceUrl", "articleIsTrue", "fkScreenshot", heading, summary, "metricsAlteration", "metricsTrue", "fbShares", "fbLikes", "fbComments", "twRetweets", "twLikes") VALUES
    (group_id, 'https://www.wired.com/story/lone-star-tick-that-gives-people-meat-allergies-may-be-spreading', TRUE , image_id, 'Fleischallergie nach Zeckenbiss', ' In the last decade and a half, thousands of previously protein-loving Americans have developed a dangerous allergy to meat. And they all have one thing in common: the lone star tick.', 0, TRUE ,  115564,  NULL,  NULL,  123,  13046),
        (group_id, 'https://www.wired.com/story/lone-star-tick-that-gives-people-meat-allergies-may-be-spreading', TRUE , image_id, 'Fleischallergie nach Zeckenbiss', ' In the last decade and a half, thousands of previously protein-loving Americans have developed a dangerous allergy to meat. And they all have one thing in common: the lone star tick.', +1, FALSE ,  115564, NULL,  NULL,  1123,  13046),
    (group_id, 'https://www.wired.com/story/lone-star-tick-that-gives-people-meat-allergies-may-be-spreading', TRUE , image_id, 'Fleischallergie nach Zeckenbiss', ' In the last decade and a half, thousands of previously protein-loving Americans have developed a dangerous allergy to meat. And they all have one thing in common: the lone star tick.', -1, FALSE ,  4,  NULL,  NULL,  1,  0);

  INSERT INTO image (data, "contentType") VALUES ( http_get('https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Ruine_Pirna_Rottwerndorf_Altrottwerndorf25.JPG/800px-Ruine_Pirna_Rottwerndorf_Altrottwerndorf25.JPG'), 'image/jpeg') RETURNING id INTO image_id;
  INSERT INTO "articleGroup" (id) VALUES (DEFAULT) RETURNING id INTO group_id;
  INSERT INTO article ("fkGroup", "sourceUrl", "articleIsTrue", "fkScreenshot", heading, summary, "metricsAlteration", "metricsTrue", "fbShares", "fbLikes", "fbComments", "twRetweets", "twLikes") VALUES
    (group_id, 'http://www.abc.net.au/news/2016-12-12/no-one-home-after-seven-hour-police-standoff-in-melton/8114164', TRUE , image_id, 'Polizei belagert 7 Stunden lang leeres Haus', 'Nach 7 Stunden Belagerung musste die Polizei in Melton, bei Melbourne feststellen, dass das belagerte Haus leer war.', 0, TRUE ,  17835,  NULL,  NULL,  NULL,  NULL),
      (group_id, 'http://www.abc.net.au/news/2016-12-12/no-one-home-after-seven-hour-police-standoff-in-melton/8114164', TRUE , image_id, 'Polizei belagert 7 Stunden lang leeres Haus', 'Nach 7 Stunden Belagerung musste die Polizei in Melton, bei Melbourne feststellen, dass das belagerte Haus leer war.', +1, FALSE ,  27835,  NULL,  NULL,  NULL,  NULL),
    (group_id, 'http://www.abc.net.au/news/2016-12-12/no-one-home-after-seven-hour-police-standoff-in-melton/8114164', TRUE , image_id, 'Polizei belagert 7 Stunden lang leeres Haus', 'Nach 7 Stunden Belagerung musste die Polizei in Melton, bei Melbourne feststellen, dass das belagerte Haus leer war.', -1, FALSE ,  3,  NULL,  NULL,  NULL,  NULL);

  INSERT INTO image (data, "contentType") VALUES ( http_get('https://cdn.pixabay.com/photo/2012/06/18/01/07/iguana-50198_960_720.jpg'), 'image/jpeg') RETURNING id INTO image_id;
  INSERT INTO "articleGroup" (id) VALUES (DEFAULT) RETURNING id INTO group_id;
  INSERT INTO article ("fkGroup", "sourceUrl", "articleIsTrue", "fkScreenshot", heading, summary, "metricsAlteration", "metricsTrue", "fbShares", "fbLikes", "fbComments", "twRetweets", "twLikes") VALUES
    (group_id, 'http://kxan.com/2017/04/19/drug-sniffing-lizard-joins-arizona-police-force', FALSE , image_id, 'Drug-sniffing lizard joins Arizona police force', 'Das Avondale Polizeidezernat in Arizona veröffentlichte Photos der Amtsvereidigung ihres neuesten und ungewöhnlichsten Beamten - Iroh, dem Drogenspürleguan. Die Bartagame kam im April im Zuge eines Pilotprojekts zum Polizeidezernat in Avondale und wurde nun von Polizeichef Dale Nannenga offiziell vereidigt.', 0, TRUE ,  1244,  NULL,  NULL,  15,  21),
        (group_id, 'http://kxan.com/2017/04/19/drug-sniffing-lizard-joins-arizona-police-force', FALSE , image_id, 'Drug-sniffing lizard joins Arizona police force', 'Das Avondale Polizeidezernat in Arizona veröffentlichte Photos der Amtsvereidigung ihres neuesten und ungewöhnlichsten Beamten - Iroh, dem Drogenspürleguan. Die Bartagame kam im April im Zuge eines Pilotprojekts zum Polizeidezernat in Avondale und wurde nun von Polizeichef Dale Nannenga offiziell vereidigt.', +1, FALSE ,  12440,  NULL,  NULL,  2882,  2322),
    (group_id, 'http://kxan.com/2017/04/19/drug-sniffing-lizard-joins-arizona-police-force', FALSE , image_id, 'Drug-sniffing lizard joins Arizona police force', 'Das Avondale Polizeidezernat in Arizona veröffentlichte Photos der Amtsvereidigung ihres neuesten und ungewöhnlichsten Beamten - Iroh, dem Drogenspürleguan. Die Bartagame kam im April im Zuge eines Pilotprojekts zum Polizeidezernat in Avondale und wurde nun von Polizeichef Dale Nannenga offiziell vereidigt.', -1, FALSE ,  2,  NULL,  NULL,  2,  0);

  INSERT INTO image (data, "contentType") VALUES ( http_get('https://cdn.pixabay.com/photo/2017/03/07/23/12/silhouette-2125521_960_720.jpg'), 'image/jpeg') RETURNING id INTO image_id;
  INSERT INTO "articleGroup" (id) VALUES (DEFAULT) RETURNING id INTO group_id;
  INSERT INTO article ("fkGroup", "sourceUrl", "articleIsTrue", "fkScreenshot", heading, summary, "metricsAlteration", "metricsTrue", "fbShares", "fbLikes", "fbComments", "twRetweets", "twLikes") VALUES
    (group_id, 'http://www.snopes.com/pregnant/youngestmother.asp', TRUE , image_id, 'Jüngste Mutter mit 5 Jahren', 'Die jüngste aktenkundige Mutter war ein erst 5 Jahre altes peruanisches Mädchen.', 0, TRUE ,  3311,  NULL,  NULL,  NULL,  11),
        (group_id, 'http://www.snopes.com/pregnant/youngestmother.asp', TRUE , image_id, 'Jüngste Mutter mit 5 Jahren', 'Die jüngste aktenkundige Mutter war ein erst 5 Jahre altes peruanisches Mädchen.', +1, FALSE ,  8312,  NULL,  NULL,  NULL,  3442),
    (group_id, 'http://www.snopes.com/pregnant/youngestmother.asp', TRUE , image_id, 'Jüngste Mutter mit 5 Jahren', 'Die jüngste aktenkundige Mutter war ein erst 5 Jahre altes peruanisches Mädchen.', -1, FALSE ,  3,  NULL,  NULL,  NULL,  3);

  INSERT INTO image (data, "contentType") VALUES ( http_get('https://upload.wikimedia.org/wikipedia/de/b/b8/Libelle_Berlin_080514.jpg'), 'image/jpeg') RETURNING id INTO image_id;
  INSERT INTO "articleGroup" (id) VALUES (DEFAULT) RETURNING id INTO group_id;
  INSERT INTO article ("fkGroup", "sourceUrl", "articleIsTrue", "fkScreenshot", heading, summary, "metricsAlteration", "metricsTrue", "fbShares", "fbLikes", "fbComments", "twRetweets", "twLikes") VALUES
    (group_id, 'https://www.newscientist.com/article/2129185-female-dragonflies-fake-sudden-death-to-avoid-male-advances/', TRUE , image_id, 'Weibliche Libellen täuschen Tod vor, um Verehrern zu entkommen', 'Weibliche Libellen wenden eine extreme Taktik an, um unliebsamen Verehrern zu entkommen: sie lassen sich aus der Luft fallen und stellen sich dann tot.', 0, TRUE ,  241973,  NULL,  NULL,  772,  1100),
    (group_id, 'https://www.newscientist.com/article/2129185-female-dragonflies-fake-sudden-death-to-avoid-male-advances/', TRUE , image_id, 'Weibliche Libellen täuschen Tod vor, um Verehrern zu entkommen', 'Weibliche Libellen wenden eine extreme Taktik an, um unliebsamen Verehrern zu entkommen: sie lassen sich aus der Luft fallen und stellen sich dann tot.', +1, FALSE ,  341973,  NULL,  NULL,  973,  1600),
    (group_id, 'https://www.newscientist.com/article/2129185-female-dragonflies-fake-sudden-death-to-avoid-male-advances/', TRUE , image_id, 'Weibliche Libellen täuschen Tod vor, um Verehrern zu entkommen', 'Weibliche Libellen wenden eine extreme Taktik an, um unliebsamen Verehrern zu entkommen: sie lassen sich aus der Luft fallen und stellen sich dann tot.', -1, FALSE ,  12,  NULL,  NULL,  2,  4);

  INSERT INTO image (data, "contentType") VALUES ( http_get('https://cdn.pixabay.com/photo/2011/01/17/17/38/golden-mantled-ground-squirrel-4588_960_720.jpg'), 'image/jpeg') RETURNING id INTO image_id;
  INSERT INTO "articleGroup" (id) VALUES (DEFAULT) RETURNING id INTO group_id;
  INSERT INTO article ("fkGroup", "sourceUrl", "articleIsTrue", "fkScreenshot", heading, summary, "metricsAlteration", "metricsTrue", "fbShares", "fbLikes", "fbComments", "twRetweets", "twLikes") VALUES
    (group_id, 'http://www.independent.co.uk/environment/prince-charles-squirrels-nutella-sterilise-plans-backs-grey-red-a7597481.html', TRUE , image_id, 'Prince Charles backs plan to use Nutella as bait to sterilise grey squirrels', 'Prince Charles has backed a government plan to sterilise grey squirrels using traps filled with Nutella, in a bid to protect their smaller red cousins.', 0, TRUE ,  616,  NULL,  NULL,  25,  120),
        (group_id, 'http://www.independent.co.uk/environment/prince-charles-squirrels-nutella-sterilise-plans-backs-grey-red-a7597481.html', TRUE , image_id, 'Prince Charles backs plan to use Nutella as bait to sterilise grey squirrels', 'Prince Charles has backed a government plan to sterilise grey squirrels using traps filled with Nutella, in a bid to protect their smaller red cousins.', +1, FALSE ,  6162,  NULL,  NULL,  250,  1207),
    (group_id, 'http://www.independent.co.uk/environment/prince-charles-squirrels-nutella-sterilise-plans-backs-grey-red-a7597481.html', TRUE , image_id, 'Prince Charles backs plan to use Nutella as bait to sterilise grey squirrels', 'Prince Charles has backed a government plan to sterilise grey squirrels using traps filled with Nutella, in a bid to protect their smaller red cousins.', -1, FALSE ,  4,  NULL,  NULL,  1,  1);

  INSERT INTO image (data, "contentType") VALUES ( http_get('https://vignette.wikia.nocookie.net/breakingbad/images/4/46/Cast_bb_800x600_walter-white.jpg'), 'image/jpeg') RETURNING id INTO image_id;
  INSERT INTO "articleGroup" (id) VALUES (DEFAULT) RETURNING id INTO group_id;
  INSERT INTO article ("fkGroup", "sourceUrl", "articleIsTrue", "fkScreenshot", heading, summary, "metricsAlteration", "metricsTrue", "fbShares", "fbLikes", "fbComments", "twRetweets", "twLikes") VALUES
    (group_id, 'https://www.baysidestarnews.com.au/news/judge-praises-drug-dealer-its-good-business-model/3171155', TRUE , image_id, 'Richter lobt Drogendealer für Geschäftsmodell', 'Eine Richterin in Queensland hat einen Methamphetamin-Dealer für sein tüchtiges Geschäftsmodell gelobt. Richterin Ann Lyons sagte Brodie Gary Satterley, dass es offensichtlich nicht in der besten Branche ist, aber ein gutes Geschäftsmodell.', 0, TRUE ,  616,  NULL,  NULL,  25,  120),
        (group_id, 'https://www.baysidestarnews.com.au/news/judge-praises-drug-dealer-its-good-business-model/3171155', TRUE , image_id, 'Richter lobt Drogendealer für Geschäftsmodell', 'Eine Richterin in Queensland hat einen Methamphetamin-Dealer für sein tüchtiges Geschäftsmodell gelobt. Richterin Ann Lyons sagte Brodie Gary Satterley, dass es offensichtlich nicht in der besten Branche ist, aber ein gutes Geschäftsmodell.', +1, FALSE ,  6164,  NULL,  NULL,  2511,  6231),
    (group_id, 'https://www.baysidestarnews.com.au/news/judge-praises-drug-dealer-its-good-business-model/3171155', TRUE , image_id, 'Richter lobt Drogendealer für Geschäftsmodell', 'Eine Richterin in Queensland hat einen Methamphetamin-Dealer für sein tüchtiges Geschäftsmodell gelobt. Richterin Ann Lyons sagte Brodie Gary Satterley, dass es offensichtlich nicht in der besten Branche ist, aber ein gutes Geschäftsmodell.', -1, FALSE ,  2,  NULL,  NULL,  1,  1);

  INSERT INTO image (data, "contentType") VALUES ( http_get('http://freshrestaurants.com/wp-content/uploads/2016/03/iStock_000005724686Large.jpg'), 'image/jpeg') RETURNING id INTO image_id;
  INSERT INTO "articleGroup" (id) VALUES (DEFAULT) RETURNING id INTO group_id;
  INSERT INTO article ("fkGroup", "sourceUrl", "articleIsTrue", "fkScreenshot", heading, summary, "metricsAlteration", "metricsTrue", "fbShares", "fbLikes", "fbComments", "twRetweets", "twLikes") VALUES
    (group_id, 'https://ourworldindata.org/war-and-peace', TRUE , image_id, 'Wir leben in der friedlichsten Zeit seit Menscheit existiert', 'Daten zeigen, dass die Menscheit noch nie in so friedlichen Zeiten lebte wie aktuell.', 0, TRUE ,  884,  NULL,  NULL,  25,  406),
        (group_id, 'https://ourworldindata.org/war-and-peace', TRUE , image_id, 'Wir leben in der friedlichsten Zeit seit Menscheit existiert', 'Daten zeigen, dass die Menscheit noch nie in so friedlichen Zeiten lebte wie aktuell', +1, FALSE ,  32488,  NULL,  NULL,  257,  638),
    (group_id, 'https://ourworldindata.org/war-and-peace', TRUE , image_id, 'Wir leben in der friedlichsten Zeit seit Menscheit existiert', 'Daten zeigen, dass die Menscheit noch nie in so friedlichen Zeiten lebte wie aktuell', -1, FALSE ,  2,  NULL,  NULL,  1,  1);

  INSERT INTO image (data, "contentType") VALUES ( http_get('https://vignette4.wikia.nocookie.net/the-silence-of-the-lambs/images/c/c0/Hannibal_1.jpg'), 'image/jpeg') RETURNING id INTO image_id;
  INSERT INTO "articleGroup" (id) VALUES (DEFAULT) RETURNING id INTO group_id;
  INSERT INTO article ("fkGroup", "sourceUrl", "articleIsTrue", "fkScreenshot", heading, summary, "metricsAlteration", "metricsTrue", "fbShares", "fbLikes", "fbComments", "twRetweets", "twLikes") VALUES
    (group_id, 'http://www.spiegel.de/wissenschaft/mensch/kannibalismus-im-kaloriencheck-naehrwerte-von-mensch-und-tier-a-1141957.html', TRUE , image_id, 'Nährwert von Menschenfleisch: Kannibalismus zahlt sich nicht aus', 'In der Steinzeit sollen hier und da Kannibalen am Werk gewesen sein, glauben Archäologen. Doch wie nahrhaft war ein Urmensch überhaupt? Ein Forscher hat nun eine makabere Kalorienrechnung aufgemacht.', 0, TRUE ,  216,  NULL,  NULL,  4,  40),
    (group_id, 'http://www.spiegel.de/wissenschaft/mensch/kannibalismus-im-kaloriencheck-naehrwerte-von-mensch-und-tier-a-1141957.html', TRUE , image_id, 'Nährwert von Menschenfleisch: Kannibalismus zahlt sich nicht aus', 'In der Steinzeit sollen hier und da Kannibalen am Werk gewesen sein, glauben Archäologen. Doch wie nahrhaft war ein Urmensch überhaupt? Ein Forscher hat nun eine makabere Kalorienrechnung aufgemacht.', +1, FALSE ,  81301,  NULL,  NULL,  23141,  23423),
    (group_id, 'http://www.spiegel.de/wissenschaft/mensch/kannibalismus-im-kaloriencheck-naehrwerte-von-mensch-und-tier-a-1141957.html', TRUE , image_id, 'Nährwert von Menschenfleisch: Kannibalismus zahlt sich nicht aus', 'In der Steinzeit sollen hier und da Kannibalen am Werk gewesen sein, glauben Archäologen. Doch wie nahrhaft war ein Urmensch überhaupt? Ein Forscher hat nun eine makabere Kalorienrechnung aufgemacht.', -1, FALSE ,  21,  NULL,  NULL,  1,  0);

  INSERT INTO image (data, "contentType") VALUES ( http_get('https://cdn.pixabay.com/photo/2015/05/04/15/25/firefighter-752540_960_720.jpg'), 'image/jpeg') RETURNING id INTO image_id;
  INSERT INTO "articleGroup" (id) VALUES (DEFAULT) RETURNING id INTO group_id;
  INSERT INTO article ("fkGroup", "sourceUrl", "articleIsTrue", "fkScreenshot", heading, summary, "metricsAlteration", "metricsTrue", "fbShares", "fbLikes", "fbComments", "twRetweets", "twLikes") VALUES
    (group_id, 'https://consumerist.com/2017/02/08/factory-that-made-samsung-galaxy-note-7-batteries-catches-fire-yes-really', TRUE , image_id, 'Factory That Made Samsung Galaxy Note 7 Batteries Catches Fire (Yes, Really)', 'Eine Fabrik in China, die Akkus für das Galaxy Note 7 hergestellt hat - aufgelassen wegen der Tendenz der Akkus zu explodieren - ist nun selbst Opfer der Flammen geworden.', 0, TRUE ,  1874,  NULL,  NULL,  NULL,  43),
    (group_id, 'https://consumerist.com/2017/02/08/factory-that-made-samsung-galaxy-note-7-batteries-catches-fire-yes-really', TRUE , image_id, 'Factory That Made Samsung Galaxy Note 7 Batteries Catches Fire (Yes, Really)', 'Eine Fabrik in China, die Akkus für das Galaxy Note 7 hergestellt hat - aufgelassen wegen der Tendenz der Akkus zu explodieren - ist nun selbst Opfer der Flammen geworden.', +1, FALSE ,  18740,  NULL,  NULL,  4130,  4198),
    (group_id, 'https://consumerist.com/2017/02/08/factory-that-made-samsung-galaxy-note-7-batteries-catches-fire-yes-really', TRUE , image_id, 'Factory That Made Samsung Galaxy Note 7 Batteries Catches Fire (Yes, Really)', 'Eine Fabrik in China, die Akkus für das Galaxy Note 7 hergestellt hat - aufgelassen wegen der Tendenz der Akkus zu explodieren - ist nun selbst Opfer der Flammen geworden.', -1, FALSE ,  2,  1,  2,  1,  1);

  INSERT INTO image (data, "contentType") VALUES ( http_get('https://farm4.staticflickr.com/3863/14837259957_ee1516134a_k_d.jpg'), 'image/jpeg') RETURNING id INTO image_id;
  INSERT INTO "articleGroup" (id) VALUES (DEFAULT) RETURNING id INTO group_id;
  INSERT INTO article ("fkGroup", "sourceUrl", "articleIsTrue", "fkScreenshot", heading, summary, "metricsAlteration", "metricsTrue", "fbShares", "fbLikes", "fbComments", "twRetweets", "twLikes") VALUES
    (group_id, 'https://kurier.at/leben/hater-dating-app-fuer-menschen-die-dieselben-dinge-hassen/244.610.244', TRUE , image_id, 'Dating-App für Menschen, die dieselben Dinge hassen', 'Nach Bumble, Whispar und 3nder kommt jetzt Hater, eine Dating-App à la Tinder für Menschen, die dieselben Dinge verabscheuen.', 0, TRUE ,  8,  NULL,  NULL,  NULL,  NULL),
    (group_id, 'https://kurier.at/leben/hater-dating-app-fuer-menschen-die-dieselben-dinge-hassen/244.610.244', TRUE , image_id, 'Dating-App für Menschen, die dieselben Dinge hassen', 'Nach Bumble, Whispar und 3nder kommt jetzt Hater, eine Dating-App à la Tinder für Menschen, die dieselben Dinge verabscheuen.', +1, FALSE ,  862,  2633,  NULL,  8929,  7305),
    (group_id, 'https://kurier.at/leben/hater-dating-app-fuer-menschen-die-dieselben-dinge-hassen/244.610.244', TRUE , image_id, 'Dating-App für Menschen, die dieselben Dinge hassen', 'Nach Bumble, Whispar und 3nder kommt jetzt Hater, eine Dating-App à la Tinder für Menschen, die dieselben Dinge verabscheuen.', -1, FALSE ,  2,  NULL,  NULL,  0,  0);

  INSERT INTO image (data, "contentType") VALUES ( http_get('https://cdn.pixabay.com/photo/2015/07/17/15/40/colourful-condoms-849409_960_720.jpg'), 'image/jpeg') RETURNING id INTO image_id;
  INSERT INTO "articleGroup" (id) VALUES (DEFAULT) RETURNING id INTO group_id;
  INSERT INTO article ("fkGroup", "sourceUrl", "articleIsTrue", "fkScreenshot", heading, summary, "metricsAlteration", "metricsTrue", "fbShares", "fbLikes", "fbComments", "twRetweets", "twLikes") VALUES
    (group_id, 'http://www.taz.de/Kirche-beim-Christopher-Street-Day/!5423867', FALSE , image_id, 'Kondome mit Luthers Segen', 'Beim Berliner CSD wird die Evangelische Kirche erstmals mit einem Partywagen dabei sein. Gleitgel und Kondome sollen geworfen werden.', 0, TRUE ,  1562,  0,  0,  1,  6),
    (group_id, 'http://www.taz.de/Kirche-beim-Christopher-Street-Day/!5423867', FALSE , image_id, 'Kondome mit Luthers Segen', 'Beim Berliner CSD wird die Evangelische Kirche erstmals mit einem Partywagen dabei sein. Gleitgel und Kondome sollen geworfen werden.', +1, FALSE ,  18221,  93171,  NULL,  10993,  11301),
    (group_id, 'http://www.taz.de/Kirche-beim-Christopher-Street-Day/!5423867', FALSE , image_id, 'Kondome mit Luthers Segen', 'Beim Berliner CSD wird die Evangelische Kirche erstmals mit einem Partywagen dabei sein. Gleitgel und Kondome sollen geworfen werden.', -1, FALSE ,  3,  5,  0,  1,  1);

  INSERT INTO image (data, "contentType") VALUES ( http_get('https://cdn.pixabay.com/photo/2017/07/24/14/22/drivers-license-2534805_960_720.jpg'), 'image/jpeg') RETURNING id INTO image_id;
  INSERT INTO "articleGroup" (id) VALUES (DEFAULT) RETURNING id INTO group_id;
  INSERT INTO article ("fkGroup", "sourceUrl", "articleIsTrue", "fkScreenshot", heading, summary, "metricsAlteration", "metricsTrue", "fbShares", "fbLikes", "fbComments", "twRetweets", "twLikes") VALUES
    (group_id, 'votum24.votum1.de/de/politik/deutsche-steuerzahler-blechen-auch-noch-fuer-fuehrerscheinerwerb-durch-migranten', FALSE , image_id, 'Führerschein für Flüchtlinge kostenlos', 'Die Bundesvereinigung der Fahrlehrerverbände (BVF) verzeichnet einen Ansturm von Asylbewerbern auf Fahrschulen. Der Grund für diesen Ansturm lässt sich leicht erklären. Die Kosten der Fahrausbildung übernimmt das Jobcenter.', 0, TRUE ,  77814,  NULL,  NULL,  NULL,  214),
    (group_id, 'votum24.votum1.de/de/politik/deutsche-steuerzahler-blechen-auch-noch-fuer-fuehrerscheinerwerb-durch-migranten', FALSE , image_id, 'Führerschein für Flüchtlinge kostenlos', 'Die Bundesvereinigung der Fahrlehrerverbände (BVF) verzeichnet einen Ansturm von Asylbewerbern auf Fahrschulen. Der Grund für diesen Ansturm lässt sich leicht erklären. Die Kosten der Fahrausbildung übernimmt das Jobcenter.', +1, FALSE ,  34523,  45334,  NULL,  NULL,  532),
    (group_id, 'votum24.votum1.de/de/politik/deutsche-steuerzahler-blechen-auch-noch-fuer-fuehrerscheinerwerb-durch-migranten', FALSE , image_id, 'Führerschein für Flüchtlinge kostenlos', 'Die Bundesvereinigung der Fahrlehrerverbände (BVF) verzeichnet einen Ansturm von Asylbewerbern auf Fahrschulen. Der Grund für diesen Ansturm lässt sich leicht erklären. Die Kosten der Fahrausbildung übernimmt das Jobcenter.', -1, FALSE ,  4,  NULL,  0,  4,  3);

  INSERT INTO image (data, "contentType") VALUES ( http_get('https://cdn.pixabay.com/photo/2016/01/21/18/46/grille-1154444_960_720.jpg'), 'image/jpeg') RETURNING id INTO image_id;
  INSERT INTO "articleGroup" (id) VALUES (DEFAULT) RETURNING id INTO group_id;
  INSERT INTO article ("fkGroup", "sourceUrl", "articleIsTrue", "fkScreenshot", heading, summary, "metricsAlteration", "metricsTrue", "fbShares", "fbLikes", "fbComments", "twRetweets", "twLikes") VALUES
    (group_id, 'http://www.das-unbekannte.de/wenn-man-grillen-geraeusche-verlangsamt-entdeckt-man-etwas-unerwartetes/', FALSE , image_id, 'Verlangsamtes Grillenzirpen klingt wie ein menschlicher Chor', 'Jim Wilson, ein Komponist, machte zufällig eine sehr erstaunliche Entdeckung. Er nahm das Zirpen von Grillen auf, verlangsamte die Aufnahme anschließend und konnte seinen Ohren nicht trauen. Die Aufnahme hörte sich an wie ein Chor aus menschlichen Stimmen.', 0, TRUE ,  25095,  NULL,  NULL,  NULL,  NULL),
    (group_id, 'http://www.das-unbekannte.de/wenn-man-grillen-geraeusche-verlangsamt-entdeckt-man-etwas-unerwartetes/', FALSE , image_id, 'Verlangsamtes Grillenzirpen klingt wie ein menschlicher Chor', 'Jim Wilson, ein Komponist, machte zufällig eine sehr erstaunliche Entdeckung. Er nahm das Zirpen von Grillen auf, verlangsamte die Aufnahme anschließend und konnte seinen Ohren nicht trauen. Die Aufnahme hörte sich an wie ein Chor aus menschlichen Stimmen.', +1, FALSE ,  25095,  201032,  NULL,  NULL,  NULL),
    (group_id, 'http://www.das-unbekannte.de/wenn-man-grillen-geraeusche-verlangsamt-entdeckt-man-etwas-unerwartetes/', FALSE , image_id, 'Verlangsamtes Grillenzirpen klingt wie ein menschlicher Chor', 'Jim Wilson, ein Komponist, machte zufällig eine sehr erstaunliche Entdeckung. Er nahm das Zirpen von Grillen auf, verlangsamte die Aufnahme anschließend und konnte seinen Ohren nicht trauen. Die Aufnahme hörte sich an wie ein Chor aus menschlichen Stimmen.', -1, FALSE ,  12,  0,  0,  1,  1);

  INSERT INTO image (data, "contentType") VALUES ( http_get('https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Molly_Luft.jpg/1280px-Molly_Luft.jpg'), 'image/jpeg') RETURNING id INTO image_id;
  INSERT INTO "articleGroup" (id) VALUES (DEFAULT) RETURNING id INTO group_id;
  INSERT INTO article ("fkGroup", "sourceUrl", "articleIsTrue", "fkScreenshot", heading, summary, "metricsAlteration", "metricsTrue", "fbShares", "fbLikes", "fbComments", "twRetweets", "twLikes") VALUES
    (group_id, 'http://erstaunlich.at/index.php?option=com_content&view=article&id=3316%3Afreikarte-fuer-bordellbesuch-vom-sozialamt&catid=1%3Aerstaunliches&Itemid=1', FALSE , image_id, 'Freikarte für Bordellbesuch vom Sozialamt', 'Wie uns aus einer sehr zuverlässigen  Quelle mitgeteilt wurde,  soll das Sozialamt Graz Gutscheine  für Bordellbesuche vergeben.  Diese gelten allerdings nicht in den Hauptstoßzeiten.', 0, TRUE ,  39,  NULL,  NULL,  NULL,  NULL),
    (group_id, 'http://erstaunlich.at/index.php?option=com_content&view=article&id=3316%3Afreikarte-fuer-bordellbesuch-vom-sozialamt&catid=1%3Aerstaunliches&Itemid=1', FALSE , image_id, 'Freikarte für Bordellbesuch vom Sozialamt', 'Wie uns aus einer sehr zuverlässigen  Quelle mitgeteilt wurde,  soll das Sozialamt Graz Gutscheine  für Bordellbesuche vergeben.  Diese gelten allerdings nicht in den Hauptstoßzeiten.', +1, FALSE ,  3151,  NULL,  NULL,  1821,  534),
    (group_id, 'http://erstaunlich.at/index.php?option=com_content&view=article&id=3316%3Afreikarte-fuer-bordellbesuch-vom-sozialamt&catid=1%3Aerstaunliches&Itemid=1', FALSE , image_id, 'Freikarte für Bordellbesuch vom Sozialamt', 'Wie uns aus einer sehr zuverlässigen  Quelle mitgeteilt wurde,  soll das Sozialamt Graz Gutscheine  für Bordellbesuche vergeben.  Diese gelten allerdings nicht in den Hauptstoßzeiten.', -1, FALSE ,  12,  2,  0,  1,  1);

  INSERT INTO image (data, "contentType") VALUES ( http_get('https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/FH_Vorarlberg_Bankomat.jpg/800px-FH_Vorarlberg_Bankomat.jpg'), 'image/jpeg') RETURNING id INTO image_id;
  INSERT INTO "articleGroup" (id) VALUES (DEFAULT) RETURNING id INTO group_id;
  INSERT INTO article ("fkGroup", "sourceUrl", "articleIsTrue", "fkScreenshot", heading, summary, "metricsAlteration", "metricsTrue", "fbShares", "fbLikes", "fbComments", "twRetweets", "twLikes") VALUES
    (group_id, 'https://www.facebook.com/photo.php?fbid=1816655728601073', FALSE , image_id, 'PIN am Bankomat rückwärts eintippen löst Polizeinotruf aus', 'Werden Sie während eines Raubüberfalles dazu gezwungen, Geld vom Bankomaten abzuheben, geben Sie die PIN rückwärts (z.B. 4321 statt 1234) ein. Der Automat alarmiert sofort die Polizei. Jeder Bankomat hat diese Funktion.', 0, TRUE ,  1729886,  37772,  NULL,  NULL,  NULL),
    (group_id, 'https://www.facebook.com/photo.php?fbid=1816655728601073', FALSE , image_id, 'PIN am Bankomat rückwärts eintippen löst Polizeinotruf aus', 'Werden Sie während eines Raubüberfalles dazu gezwungen, Geld vom Bankomaten abzuheben, geben Sie die PIN rückwärts (z.B. 4321 statt 1234) ein. Der Automat alarmiert sofort die Polizei. Jeder Bankomat hat diese Funktion.', +1, FALSE ,  1729886,  37772,  NULL,  NULL,  NULL),
    (group_id, 'https://www.facebook.com/photo.php?fbid=1816655728601073', FALSE , image_id, 'PIN am Bankomat rückwärts eintippen löst Polizeinotruf aus', 'Werden Sie während eines Raubüberfalles dazu gezwungen, Geld vom Bankomaten abzuheben, geben Sie die PIN rückwärts (z.B. 4321 statt 1234) ein. Der Automat alarmiert sofort die Polizei. Jeder Bankomat hat diese Funktion.', -1, FALSE ,  11,  22,  NULL,  NULL,  NULL);

  INSERT INTO image (data, "contentType") VALUES ( http_get('https://cdn.pixabay.com/photo/2012/11/30/16/46/island-68081_960_720.jpg'), 'image/jpeg') RETURNING id INTO image_id;
  INSERT INTO "articleGroup" (id) VALUES (DEFAULT) RETURNING id INTO group_id;
  INSERT INTO article ("fkGroup", "sourceUrl", "articleIsTrue", "fkScreenshot", heading, summary, "metricsAlteration", "metricsTrue", "fbShares", "fbLikes", "fbComments", "twRetweets", "twLikes") VALUES
    (group_id, 'www.krone.at/oesterreich/mehrere-waffen-in-versteck-auf-donauinsel-gefunden-vor-donauinselfest-story-575388', FALSE , image_id, 'Mehrere Waffen in Versteck auf Donauinsel gefunden', 'Nur wenige Stunden vor Beginn des 34. Donauinselfest gibt es Aufregung um einen brisanten Fund: In einem Versteck auf der Donauinsel lagen zwei Maschinenpistolen und eine Faustfeuerwaffe, wie die Krone erfuhr. Ob es einen Zusammenhang mit der Riesenveranstaltung gibt, ist noch nicht geklärt.', 0, TRUE ,  145,  NULL,  NULL,  NULL,  NULL),
    (group_id, 'www.krone.at/oesterreich/mehrere-waffen-in-versteck-auf-donauinsel-gefunden-vor-donauinselfest-story-575388', FALSE , image_id, 'Mehrere Waffen in Versteck auf Donauinsel gefunden', 'Nur wenige Stunden vor Beginn des 34. Donauinselfest gibt es Aufregung um einen brisanten Fund: In einem Versteck auf der Donauinsel lagen zwei Maschinenpistolen und eine Faustfeuerwaffe, wie die Krone erfuhr. Ob es einen Zusammenhang mit der Riesenveranstaltung gibt, ist noch nicht geklärt.', +1, FALSE ,  14532,  NULL,  NULL,  3201,  3458),
    (group_id, 'www.krone.at/oesterreich/mehrere-waffen-in-versteck-auf-donauinsel-gefunden-vor-donauinselfest-story-575388', FALSE , image_id, 'Mehrere Waffen in Versteck auf Donauinsel gefunden', 'Nur wenige Stunden vor Beginn des 34. Donauinselfest gibt es Aufregung um einen brisanten Fund: In einem Versteck auf der Donauinsel lagen zwei Maschinenpistolen und eine Faustfeuerwaffe, wie die Krone erfuhr. Ob es einen Zusammenhang mit der Riesenveranstaltung gibt, ist noch nicht geklärt.', -1, FALSE ,  13,  12,  0,  4,  4);

  INSERT INTO image (data, "contentType") VALUES ( http_get('https://cdn.pixabay.com/photo/2015/08/14/13/10/woman-888409_960_720.jpg'), 'image/jpeg') RETURNING id INTO image_id;
  INSERT INTO "articleGroup" (id) VALUES (DEFAULT) RETURNING id INTO group_id;
  INSERT INTO article ("fkGroup", "sourceUrl", "articleIsTrue", "fkScreenshot", heading, summary, "metricsAlteration", "metricsTrue", "fbShares", "fbLikes", "fbComments", "twRetweets", "twLikes") VALUES
    (group_id, 'http://www.heute.at/oesterreich/oberoesterreich/story/Frau-lie--sich-Zelle-von-Hund-in-Eizelle-einsetzen-59767881', TRUE , image_id, 'Frau ließ sich Zelle von Hund einsetzen', 'Im Rahmen eines Kunstprojekts wurde eine Eizelle der Künstlerin von Experten in einem Labor "entkernt" und darin eine Körperzelle ihres Hundes einpflanzt.', 0, TRUE ,  201,  NULL,  NULL,  2,  46),
    (group_id, 'http://www.heute.at/oesterreich/oberoesterreich/story/Frau-lie--sich-Zelle-von-Hund-in-Eizelle-einsetzen-59767881', TRUE , image_id, 'Frau ließ sich Zelle von Hund einsetzen', 'Im Rahmen eines Kunstprojekts wurde eine Eizelle der Künstlerin von Experten in einem Labor "entkernt" und darin eine Körperzelle ihres Hundes einpflanzt.', +1, FALSE ,  1201,  NULL,  NULL,  523,  622),
    (group_id, 'http://www.heute.at/oesterreich/oberoesterreich/story/Frau-lie--sich-Zelle-von-Hund-in-Eizelle-einsetzen-59767881', TRUE , image_id, 'Frau ließ sich Zelle von Hund einsetzen', 'Im Rahmen eines Kunstprojekts wurde eine Eizelle der Künstlerin von Experten in einem Labor "entkernt" und darin eine Körperzelle ihres Hundes einpflanzt.', -1, FALSE ,  2,  NULL,  NULL,  1,  0);

  INSERT INTO image (data, "contentType") VALUES ( http_get('https://cdn.pixabay.com/photo/2015/09/27/12/51/rice-960627_960_720.jpg'), 'image/jpeg') RETURNING id INTO image_id;
  INSERT INTO "articleGroup" (id) VALUES (DEFAULT) RETURNING id INTO group_id;
  INSERT INTO article ("fkGroup", "sourceUrl", "articleIsTrue", "fkScreenshot", heading, summary, "metricsAlteration", "metricsTrue", "fbShares", "fbLikes", "fbComments", "twRetweets", "twLikes") VALUES
    (group_id, 'https://netzfrauen.org/2017/06/09/plastik-reis/', FALSE , image_id, 'Gefälschter Reis aus Plastik', 'August 2016 veröffentlichte die Europäische Behörde für Lebensmittelsicherheit (EFSA) ihren Jahresbericht über aufkommende Risiken. Unter den Top 10 Risiken: Plastik-Reis.', 0, TRUE ,  5629,  NULL,  NULL,  4,  4),
    (group_id, 'https://netzfrauen.org/2017/06/09/plastik-reis/', FALSE , image_id, 'Gefälschter Reis aus Plastik', 'August 2016 veröffentlichte die Europäische Behörde für Lebensmittelsicherheit (EFSA) ihren Jahresbericht über aufkommende Risiken. Unter den Top 10 Risiken: Plastik-Reis.', +1, FALSE ,  5629,  NULL,  NULL,  3214,  2112),
    (group_id, 'https://netzfrauen.org/2017/06/09/plastik-reis/', FALSE , image_id, 'Gefälschter Reis aus Plastik', 'August 2016 veröffentlichte die Europäische Behörde für Lebensmittelsicherheit (EFSA) ihren Jahresbericht über aufkommende Risiken. Unter den Top 10 Risiken: Plastik-Reis.', -1, FALSE ,  4,  NULL,  NULL,  2,  0);

  INSERT INTO image (data, "contentType") VALUES ( http_get('https://cdn.pixabay.com/photo/2015/01/11/14/34/christmas-present-596300_960_720.jpg'), 'image/jpeg') RETURNING id INTO image_id;
  INSERT INTO "articleGroup" (id) VALUES (DEFAULT) RETURNING id INTO group_id;
  INSERT INTO article ("fkGroup", "sourceUrl", "articleIsTrue", "fkScreenshot", heading, summary, "metricsAlteration", "metricsTrue", "fbShares", "fbLikes", "fbComments", "twRetweets", "twLikes") VALUES
    (group_id, 'http://worldnewsdailyreport.com/7-year-old-girl-receives-breast-implants-for-christmas/', FALSE , image_id, '7-Jährige bekam Brustimplantate zu Weihnachten geschenkt', 'Juliet Manson aus Glendale, Kalifornien bekam dieses Jahr zu Weihnachten von ihrer Mutter ein ganz besonderes Geschenk: eine Reise nach China, um sich einer Brustvergrößerung zu unterziehen.', 0, TRUE ,  39358,  NULL,  NULL,  NULL,  13),
    (group_id, 'http://worldnewsdailyreport.com/7-year-old-girl-receives-breast-implants-for-christmas/', FALSE , image_id, '7-Jährige bekam Brustimplantate zu Weihnachten geschenkt', 'Juliet Manson aus Glendale, Kalifornien bekam dieses Jahr zu Weihnachten von ihrer Mutter ein ganz besonderes Geschenk: eine Reise nach China, um sich einer Brustvergrößerung zu unterziehen.', +1, FALSE ,  39358,  NULL,  NULL,  NULL,  1292),
    (group_id, 'http://worldnewsdailyreport.com/7-year-old-girl-receives-breast-implants-for-christmas/', FALSE , image_id, '7-Jährige bekam Brustimplantate zu Weihnachten geschenkt', 'Juliet Manson aus Glendale, Kalifornien bekam dieses Jahr zu Weihnachten von ihrer Mutter ein ganz besonderes Geschenk: eine Reise nach China, um sich einer Brustvergrößerung zu unterziehen.', -1, FALSE ,  8,  NULL,  NULL,  NULL,  2);

  INSERT INTO image (data, "contentType") VALUES ( http_get('https://cdn.pixabay.com/photo/2015/03/23/01/40/blindworm-685445_960_720.jpg'), 'image/jpeg') RETURNING id INTO image_id;
  INSERT INTO "articleGroup" (id) VALUES (DEFAULT) RETURNING id INTO group_id;
  INSERT INTO article ("fkGroup", "sourceUrl", "articleIsTrue", "fkScreenshot", heading, summary, "metricsAlteration", "metricsTrue", "fbShares", "fbLikes", "fbComments", "twRetweets", "twLikes") VALUES
    (group_id, 'http://haynoticia.es/mujer-lleva-28-anos-haciendose-pasar-ciega-no-saludar-la-gente3333/', FALSE , image_id, 'Frau täuschte Blindheit vor - 28 Jahre lang', '57-Jährige bestätigte vor Kurzem, einen von ihren Nachbarn bereits länger gehegten Verdacht: sie habe ihre Blindheit nur vorgetäuscht. So habe sie Bekannte auf der Straße nicht mehr grüßen müssen, behauptet Carmen Jimenez', 0, TRUE ,  70173,  NULL,  NULL,  NULL,  NULL),
    (group_id, 'http://haynoticia.es/mujer-lleva-28-anos-haciendose-pasar-ciega-no-saludar-la-gente3333/', FALSE , image_id, 'Frau täuschte Blindheit vor - 28 Jahre lang', '57-Jährige bestätigte vor Kurzem, einen von ihren Nachbarn bereits länger gehegten Verdacht: sie habe ihre Blindheit nur vorgetäuscht. So habe sie Bekannte auf der Straße nicht mehr grüßen müssen, behauptet Carmen Jimenez', +1, FALSE ,  78601,  NULL,  NULL,  NULL,  NULL),
    (group_id, 'http://haynoticia.es/mujer-lleva-28-anos-haciendose-pasar-ciega-no-saludar-la-gente3333/', FALSE , image_id, 'Frau täuschte Blindheit vor - 28 Jahre lang', '57-Jährige bestätigte vor Kurzem, einen von ihren Nachbarn bereits länger gehegten Verdacht: sie habe ihre Blindheit nur vorgetäuscht. So habe sie Bekannte auf der Straße nicht mehr grüßen müssen, behauptet Carmen Jimenez', -1, FALSE ,  21,  NULL,  NULL,  NULL,  NULL));

  INSERT INTO image (data, "contentType") VALUES ( http_get('https://cdn.pixabay.com/photo/2014/01/28/08/03/witches-253596_960_720.jpg'), 'image/jpeg') RETURNING id INTO image_id;
  INSERT INTO "articleGroup" (id) VALUES (DEFAULT) RETURNING id INTO group_id;
  INSERT INTO article ("fkGroup", "sourceUrl", "articleIsTrue", "fkScreenshot", heading, summary, "metricsAlteration", "metricsTrue", "fbShares", "fbLikes", "fbComments", "twRetweets", "twLikes") VALUES
    (group_id, 'https://www.waz.de/politik/afd-mann-raet-frauenverbrennung-um-klima-zu-retten-id210539979.html', FALSE , image_id, 'AfD-Politiker Podeswa fordert Frauenverbrennungen gegen Klimawandel', 'AfD-Politiker Rainer Podeswa meint zu wissen, wie man den Klimawandel stoppen kann. Seine „Empfehlung“ im Landtag, sich im Kampf gegen den Klimawandel am „Hexenhammer“ zu orientieren, hatte für Empörung gesorgt.', 0, TRUE ,  591,  NULL,  NULL,  NULL,  NULL),
    (group_id, 'https://www.waz.de/politik/afd-mann-raet-frauenverbrennung-um-klima-zu-retten-id210539979.html', FALSE , image_id, 'AfD-Politiker Podeswa fordert Frauenverbrennungen gegen Klimawandel', 'AfD-Politiker Rainer Podeswa meint zu wissen, wie man den Klimawandel stoppen kann. Seine „Empfehlung“ im Landtag, sich im Kampf gegen den Klimawandel am „Hexenhammer“ zu orientieren, hatte für Empörung gesorgt.', +1, FALSE ,  5910,  NULL,  NULL,  NULL,  NULL)),
    (group_id, 'https://www.waz.de/politik/afd-mann-raet-frauenverbrennung-um-klima-zu-retten-id210539979.html', FALSE , image_id, 'AfD-Politiker Podeswa fordert Frauenverbrennungen gegen Klimawandel', 'AfD-Politiker Rainer Podeswa meint zu wissen, wie man den Klimawandel stoppen kann. Seine „Empfehlung“ im Landtag, sich im Kampf gegen den Klimawandel am „Hexenhammer“ zu orientieren, hatte für Empörung gesorgt.', -1, FALSE ,  5,  NULL,  NULL,  NULL,  NULL));

END
$$;
